/**
 * SIH26191 - MHA/NDMA Disaster Command System
 * Mock Realistic GIS & H3 Hexagonal Cell Dataset
 * Region: Brahmaputra River Basin Sector Alpha (Guwahati - Kamrup Floodplain)
 */

window.DISASTER_DATA = (function() {
    // 32 H3 Hexagonal Cells (Simulating Resolution 7 / 8 indexing)
    // Centered around 26.18° N, 91.75° E (Brahmaputra Flood Basin & Surrounding Foothills)
    const h3Cells = [
        {
            id: '8761892543fffff',
            name: 'Pandu Ghat Floodplain',
            sector: 'Riverbank Lowland Sector-1',
            lat: 26.1820,
            lng: 91.6850,
            elevation: 46.2, // meters
            baselineRisk: 78,
            currentRisk: 88,
            riskLevel: 'critical', // green, yellow, orange, critical
            hazardType: 'Flood',
            population: 28400,
            vulnerablePopulation: {
                total: 8240,
                infants: 2450,
                elderly: 3100,
                disabled: 1120,
                pregnant: 1570
            },
            carryingCapacity: 4500, // Safe carrying capacity in extreme event
            safeCapacityThreshold: 22000, // Normal capacity
            capacityDeficit: 23900, // population - carryingCapacity
            nearestShelter: 'Kamrup Central Relief High School',
            shelterCapacity: 5200,
            shelterDistanceKm: 3.8,
            evacuationTimeHours: 4.2,
            nearbyHospitals: ['Guwahati Medical College (6.4km)', 'Pandu Railway Hospital (1.2km)'],
            roadStatus: 'Submerged', // Open, Congested, Submerged, Damaged
            primaryRoad: 'Pandu Embankment Road (NH-27 Spur)',
            rainfallMm: 310,
            waterLevelM: 3.8,
            factors: {
                historicalDisasters: 8,
                rainfallImpact: 92,
                elevationVulnerability: 88,
                populationDensity: 94,
                infrastructureVulnerability: 85,
                distanceToEmergencyServices: 68,
                roadAccessibility: 22
            },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1)',
            targetRelocationCell: '8761892501fffff' // Khanapara Safe Ridge
        },
        {
            id: '8761892541fffff',
            name: 'Uzan Bazar Riverfront',
            sector: 'Riverbank Lowland Sector-2',
            lat: 26.1950,
            lng: 91.7520,
            elevation: 48.1,
            baselineRisk: 72,
            currentRisk: 86,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 34100,
            vulnerablePopulation: {
                total: 9800,
                infants: 2890,
                elderly: 3820,
                disabled: 1240,
                pregnant: 1850
            },
            carryingCapacity: 6200,
            safeCapacityThreshold: 28000,
            capacityDeficit: 27900,
            nearestShelter: 'Cotton University Multi-Story Complex',
            shelterCapacity: 7500,
            shelterDistanceKm: 2.4,
            evacuationTimeHours: 5.1,
            nearbyHospitals: ['Mahendra Mohan Choudhury Hospital (1.5km)', 'Narayana Super Speciality (4.2km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'MG Embankment Corridor',
            rainfallMm: 295,
            waterLevelM: 3.4,
            factors: {
                historicalDisasters: 9,
                rainfallImpact: 88,
                elevationVulnerability: 84,
                populationDensity: 96,
                infrastructureVulnerability: 80,
                distanceToEmergencyServices: 55,
                roadAccessibility: 28
            },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1)',
            targetRelocationCell: '8761892503fffff' // Dispur Capital Ridge
        },
        {
            id: '8761892545fffff',
            name: 'Amingaon Industrial Reach',
            sector: 'North Bank Industrial Basin',
            lat: 26.2100,
            lng: 91.6700,
            elevation: 51.5,
            baselineRisk: 65,
            currentRisk: 82,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 22800,
            vulnerablePopulation: {
                total: 5900,
                infants: 1650,
                elderly: 2100,
                disabled: 840,
                pregnant: 1310
            },
            carryingCapacity: 3800,
            safeCapacityThreshold: 18000,
            capacityDeficit: 19000,
            nearestShelter: 'IIT Guwahati Higher Ground Pavilion',
            shelterCapacity: 8000,
            shelterDistanceKm: 4.5,
            evacuationTimeHours: 3.8,
            nearbyHospitals: ['Narayana Superspeciality North (3.1km)'],
            roadStatus: 'Damaged',
            primaryRoad: 'North Bank Arterial Highway',
            rainfallMm: 280,
            waterLevelM: 2.9,
            factors: {
                historicalDisasters: 6,
                rainfallImpact: 84,
                elevationVulnerability: 76,
                populationDensity: 82,
                infrastructureVulnerability: 86,
                distanceToEmergencyServices: 64,
                roadAccessibility: 35
            },
            recommendedAction: 'Immediate Evacuation & Chemical Hazmat Perimeter Control',
            targetRelocationCell: '8761892505fffff' // Changsari Highland Safe Zone
        },
        {
            id: '8761892547fffff',
            name: 'Bharalumukh Inundation Basin',
            sector: 'Central Urban Basin',
            lat: 26.1750,
            lng: 91.7300,
            elevation: 47.0,
            baselineRisk: 75,
            currentRisk: 91,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 41200,
            vulnerablePopulation: {
                total: 12400,
                infants: 3700,
                elderly: 4900,
                disabled: 1600,
                pregnant: 2200
            },
            carryingCapacity: 5100,
            safeCapacityThreshold: 35000,
            capacityDeficit: 36100,
            nearestShelter: 'Sonaram Higher Secondary Relief Center',
            shelterCapacity: 4500,
            shelterDistanceKm: 1.8,
            evacuationTimeHours: 6.2,
            nearbyHospitals: ['Guwahati Medical College (5.2km)', 'Apollo Clinic Fancy Bazar (2.1km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Bharalu Sluice Gate Way',
            rainfallMm: 330,
            waterLevelM: 4.1,
            factors: {
                historicalDisasters: 10,
                rainfallImpact: 95,
                elevationVulnerability: 92,
                populationDensity: 98,
                infrastructureVulnerability: 90,
                distanceToEmergencyServices: 48,
                roadAccessibility: 18
            },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1) via Water Amphibian Units',
            targetRelocationCell: '8761892501fffff' // Khanapara Safe Ridge
        },
        {
            id: '8761892549fffff',
            name: 'Noonmati Flood Channel',
            sector: 'East Drainage Zone',
            lat: 26.1920,
            lng: 91.8010,
            elevation: 54.0,
            baselineRisk: 58,
            currentRisk: 74,
            riskLevel: 'orange', // High Risk
            hazardType: 'Flood',
            population: 26500,
            vulnerablePopulation: {
                total: 6800,
                infants: 1950,
                elderly: 2600,
                disabled: 890,
                pregnant: 1360
            },
            carryingCapacity: 12000,
            safeCapacityThreshold: 24000,
            capacityDeficit: 14500,
            nearestShelter: 'Refinery Sector Community Hall',
            shelterCapacity: 6200,
            shelterDistanceKm: 2.1,
            evacuationTimeHours: 3.5,
            nearbyHospitals: ['IOCL Hospital Noonmati (1.2km)'],
            roadStatus: 'Congested',
            primaryRoad: 'Noonmati-Sector 1 Road',
            rainfallMm: 240,
            waterLevelM: 1.8,
            factors: {
                historicalDisasters: 5,
                rainfallImpact: 76,
                elevationVulnerability: 68,
                populationDensity: 80,
                infrastructureVulnerability: 74,
                distanceToEmergencyServices: 60,
                roadAccessibility: 52
            },
            recommendedAction: 'Stage-2 Evacuation (Priority 2) & Drainage Pumping',
            targetRelocationCell: '8761892507fffff' // Narengi Hilltop Buffer
        },
        {
            id: '8761892551fffff',
            name: 'Jalukbari Lowland Junction',
            sector: 'West Transit Basin',
            lat: 26.1550,
            lng: 91.6620,
            elevation: 52.8,
            baselineRisk: 52,
            currentRisk: 68,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 19400,
            vulnerablePopulation: {
                total: 4800,
                infants: 1350,
                elderly: 1850,
                disabled: 620,
                pregnant: 980
            },
            carryingCapacity: 9500,
            safeCapacityThreshold: 17000,
            capacityDeficit: 9900,
            nearestShelter: 'Gauhati University Indoor Stadium',
            shelterCapacity: 9200,
            shelterDistanceKm: 1.5,
            evacuationTimeHours: 2.9,
            nearbyHospitals: ['Ayursundra Superspecialty (2.8km)'],
            roadStatus: 'Congested',
            primaryRoad: 'NH-27 Junction Express',
            rainfallMm: 225,
            waterLevelM: 1.4,
            factors: {
                historicalDisasters: 4,
                rainfallImpact: 70,
                elevationVulnerability: 62,
                populationDensity: 75,
                infrastructureVulnerability: 65,
                distanceToEmergencyServices: 40,
                roadAccessibility: 64
            },
            recommendedAction: 'Staged Evacuation of Low-lying Pockets to GU Stadium',
            targetRelocationCell: '8761892509fffff' // Gauhati University Ridge
        },
        {
            id: '8761892553fffff',
            name: 'Chandmari Sloped Basin',
            sector: 'Central Terrace',
            lat: 26.1880,
            lng: 91.7750,
            elevation: 58.2,
            baselineRisk: 48,
            currentRisk: 62,
            riskLevel: 'orange',
            hazardType: 'Landslide',
            population: 31000,
            vulnerablePopulation: {
                total: 7400,
                infants: 2100,
                elderly: 2900,
                disabled: 950,
                pregnant: 1450
            },
            carryingCapacity: 17500,
            safeCapacityThreshold: 28000,
            capacityDeficit: 13500,
            nearestShelter: 'Assam Engineering Institute Ground',
            shelterCapacity: 6000,
            shelterDistanceKm: 1.2,
            evacuationTimeHours: 2.6,
            nearbyHospitals: ['Dispur Polyclinic (3.4km)', 'GNRC Sixmile (5.1km)'],
            roadStatus: 'Open',
            primaryRoad: 'Rajgarh Arterial Road',
            rainfallMm: 210,
            waterLevelM: 0.9,
            factors: {
                historicalDisasters: 5,
                rainfallImpact: 65,
                elevationVulnerability: 58,
                populationDensity: 88,
                infrastructureVulnerability: 62,
                distanceToEmergencyServices: 32,
                roadAccessibility: 72
            },
            recommendedAction: 'Hillside Landslide Watch & Vulnerable Group Advisory',
            targetRelocationCell: '8761892503fffff' // Dispur Safe Ridge
        },
        {
            id: '8761892555fffff',
            name: 'Paltan Bazar Transit Hub',
            sector: 'Core Transportation Sector',
            lat: 26.1780,
            lng: 91.7510,
            elevation: 53.0,
            baselineRisk: 55,
            currentRisk: 72,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 38200,
            vulnerablePopulation: {
                total: 8900,
                infants: 2400,
                elderly: 3500,
                disabled: 1100,
                pregnant: 1900
            },
            carryingCapacity: 16000,
            safeCapacityThreshold: 34000,
            capacityDeficit: 22200,
            nearestShelter: 'Railway Community Multi-Purpose Complex',
            shelterCapacity: 8500,
            shelterDistanceKm: 0.8,
            evacuationTimeHours: 3.4,
            nearbyHospitals: ['Guwahati Central Railway Hospital (0.6km)'],
            roadStatus: 'Congested',
            primaryRoad: 'Station Road & AT Road Link',
            rainfallMm: 235,
            waterLevelM: 1.6,
            factors: {
                historicalDisasters: 6,
                rainfallImpact: 74,
                elevationVulnerability: 66,
                populationDensity: 95,
                infrastructureVulnerability: 72,
                distanceToEmergencyServices: 25,
                roadAccessibility: 58
            },
            recommendedAction: 'Restrict Train Hub Inflow, Evacuate Commercial Basement Zones',
            targetRelocationCell: '8761892503fffff' // Dispur Safe Ridge
        },
        {
            id: '8761892557fffff',
            name: 'Fatasil Slum Catchment',
            sector: 'Southwest Valley Basin',
            lat: 26.1510,
            lng: 91.7220,
            elevation: 49.5,
            baselineRisk: 70,
            currentRisk: 85,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 29500,
            vulnerablePopulation: {
                total: 9100,
                infants: 2800,
                elderly: 3400,
                disabled: 1200,
                pregnant: 1700
            },
            carryingCapacity: 4200,
            safeCapacityThreshold: 22000,
            capacityDeficit: 25300,
            nearestShelter: 'Fatasil Govt High School Camp',
            shelterCapacity: 3800,
            shelterDistanceKm: 1.1,
            evacuationTimeHours: 4.8,
            nearbyHospitals: ['Marwari Maternity Hospital (2.8km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Fatasil Ambari Main Road',
            rainfallMm: 290,
            waterLevelM: 3.2,
            factors: {
                historicalDisasters: 8,
                rainfallImpact: 89,
                elevationVulnerability: 86,
                populationDensity: 97,
                infrastructureVulnerability: 92,
                distanceToEmergencyServices: 52,
                roadAccessibility: 24
            },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1) with NDRF Boats',
            targetRelocationCell: '8761892501fffff' // Khanapara Safe Ridge
        },
        {
            id: '8761892559fffff',
            name: 'Basistha Tributary Zone',
            sector: 'South Riverway Sector',
            lat: 26.1200,
            lng: 91.7850,
            elevation: 64.0,
            baselineRisk: 42,
            currentRisk: 55,
            riskLevel: 'moderate', // Yellow
            hazardType: 'Flood',
            population: 18200,
            vulnerablePopulation: {
                total: 4100,
                infants: 1100,
                elderly: 1600,
                disabled: 520,
                pregnant: 880
            },
            carryingCapacity: 14500,
            safeCapacityThreshold: 20000,
            capacityDeficit: 3700,
            nearestShelter: 'Basistha Temple Community Shelter',
            shelterCapacity: 5000,
            shelterDistanceKm: 1.4,
            evacuationTimeHours: 1.8,
            nearbyHospitals: ['Base Hospital Army Cantonment (3.2km)'],
            roadStatus: 'Open',
            primaryRoad: 'Basistha Mandir Road',
            rainfallMm: 170,
            waterLevelM: 0.6,
            factors: {
                historicalDisasters: 3,
                rainfallImpact: 56,
                elevationVulnerability: 48,
                populationDensity: 62,
                infrastructureVulnerability: 50,
                distanceToEmergencyServices: 38,
                roadAccessibility: 78
            },
            recommendedAction: 'Monitor River Discharge & Sluice Levels, Maintain Safe Patrols',
            targetRelocationCell: '8761892501fffff'
        },
        {
            id: '8761892561fffff',
            name: 'Six Mile Urban Corridor',
            sector: 'East Central Zone',
            lat: 26.1400,
            lng: 91.8100,
            elevation: 68.5,
            baselineRisk: 35,
            currentRisk: 48,
            riskLevel: 'moderate',
            hazardType: 'Flood',
            population: 27800,
            vulnerablePopulation: {
                total: 5600,
                infants: 1500,
                elderly: 2200,
                disabled: 720,
                pregnant: 1180
            },
            carryingCapacity: 23000,
            safeCapacityThreshold: 30000,
            capacityDeficit: 4800,
            nearestShelter: 'Six Mile Flying Club Relief Center',
            shelterCapacity: 6500,
            shelterDistanceKm: 1.0,
            evacuationTimeHours: 1.5,
            nearbyHospitals: ['GNRC Medical Hospital (0.8km)', 'Downtown Hospital (2.1km)'],
            roadStatus: 'Open',
            primaryRoad: 'GS Road Flyover Corridor',
            rainfallMm: 155,
            waterLevelM: 0.3,
            factors: {
                historicalDisasters: 2,
                rainfallImpact: 50,
                elevationVulnerability: 42,
                populationDensity: 78,
                infrastructureVulnerability: 46,
                distanceToEmergencyServices: 20,
                roadAccessibility: 88
            },
            recommendedAction: 'Maintain Normal Transit, Stage Relief Supplies for Displaced Persons',
            targetRelocationCell: '8761892501fffff'
        },
        {
            id: '8761892563fffff',
            name: 'Lalmati Urban Terrace',
            sector: 'South Slope',
            lat: 26.1290,
            lng: 91.7580,
            elevation: 72.0,
            baselineRisk: 30,
            currentRisk: 42,
            riskLevel: 'moderate',
            hazardType: 'Landslide',
            population: 16400,
            vulnerablePopulation: {
                total: 3500,
                infants: 920,
                elderly: 1400,
                disabled: 460,
                pregnant: 720
            },
            carryingCapacity: 15000,
            safeCapacityThreshold: 18000,
            capacityDeficit: 1400,
            nearestShelter: 'Sarujasai Stadium Pavilion',
            shelterCapacity: 12000,
            shelterDistanceKm: 2.2,
            evacuationTimeHours: 1.4,
            nearbyHospitals: ['Excelcare Hospital (3.1km)'],
            roadStatus: 'Open',
            primaryRoad: 'National Highway Bypass Link',
            rainfallMm: 140,
            waterLevelM: 0.2,
            factors: {
                historicalDisasters: 2,
                rainfallImpact: 44,
                elevationVulnerability: 38,
                populationDensity: 58,
                infrastructureVulnerability: 42,
                distanceToEmergencyServices: 28,
                roadAccessibility: 85
            },
            recommendedAction: 'Standby Safe Reserve; Prepare for Incoming Evacuees',
            targetRelocationCell: '8761892501fffff'
        },

        // SAFE DESTINATION GREEN ZONES (High Carrying Capacity & Safe Elevation)
        {
            id: '8761892501fffff',
            name: 'Khanapara Safe Ridge',
            sector: 'Southeast High Elevation Zone',
            lat: 26.1150,
            lng: 91.8280,
            elevation: 115.0, // High ground! Safe from all flood inundation
            baselineRisk: 14,
            currentRisk: 18,
            riskLevel: 'safe', // Green Zone
            hazardType: 'Flood',
            population: 14200,
            vulnerablePopulation: {
                total: 2400,
                infants: 650,
                elderly: 980,
                disabled: 310,
                pregnant: 460
            },
            carryingCapacity: 65000, // Massive safe carrying capacity!
            safeCapacityThreshold: 75000,
            capacityDeficit: -50800, // Massive SURPLUS of 50,800 safe capacity!
            nearestShelter: 'Veterinary College Mega Relief Hub & Stadium',
            shelterCapacity: 28000,
            shelterDistanceKm: 0.5,
            evacuationTimeHours: 0.5,
            nearbyHospitals: ['Army Base Hospital (2.1km)', 'GNRC North East Medical (2.9km)', 'Dispur Hospital (3.8km)'],
            roadStatus: 'Open',
            primaryRoad: 'GS Road 6-Lane Expressway (Elevated)',
            rainfallMm: 95,
            waterLevelM: 0.0,
            factors: {
                historicalDisasters: 0,
                rainfallImpact: 20,
                elevationVulnerability: 10,
                populationDensity: 35,
                infrastructureVulnerability: 15,
                distanceToEmergencyServices: 12,
                roadAccessibility: 98
            },
            recommendedAction: 'PRIMARY RELOCATION RECEPTION ZONE: Activate Relief Beds & Food Supply Depots',
            targetRelocationCell: null
        },
        {
            id: '8761892503fffff',
            name: 'Dispur Capital Ridge',
            sector: 'Government Capitol Safe Zone',
            lat: 26.1480,
            lng: 91.7920,
            elevation: 88.0, // Safe elevation
            baselineRisk: 18,
            currentRisk: 22,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 22100,
            vulnerablePopulation: {
                total: 4100,
                infants: 1100,
                elderly: 1650,
                disabled: 510,
                pregnant: 840
            },
            carryingCapacity: 58000,
            safeCapacityThreshold: 68000,
            capacityDeficit: -35900, // Surplus of 35,900
            nearestShelter: 'Assam Secretariat High-Ground Pavilion',
            shelterCapacity: 22000,
            shelterDistanceKm: 0.7,
            evacuationTimeHours: 0.6,
            nearbyHospitals: ['Dispur Hospital (0.9km)', 'Capital Emergency Clinic (0.5km)'],
            roadStatus: 'Open',
            primaryRoad: 'Capitol Central Avenue',
            rainfallMm: 110,
            waterLevelM: 0.0,
            factors: {
                historicalDisasters: 0,
                rainfallImpact: 24,
                elevationVulnerability: 14,
                populationDensity: 45,
                infrastructureVulnerability: 18,
                distanceToEmergencyServices: 8,
                roadAccessibility: 96
            },
            recommendedAction: 'SECONDARY RELOCATION DESTINATION: Coordinate Logistics & Health Staging',
            targetRelocationCell: null
        },
        {
            id: '8761892505fffff',
            name: 'Changsari Highland Safe Zone',
            sector: 'North Bank Safe Foothills',
            lat: 26.2650,
            lng: 91.7050,
            elevation: 124.0,
            baselineRisk: 12,
            currentRisk: 15,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 11500,
            vulnerablePopulation: {
                total: 1900,
                infants: 480,
                elderly: 750,
                disabled: 260,
                pregnant: 410
            },
            carryingCapacity: 48000,
            safeCapacityThreshold: 55000,
            capacityDeficit: -36500, // Surplus of 36,500
            nearestShelter: 'AIIMS Guwahati Super Campus Shelter',
            shelterCapacity: 25000,
            shelterDistanceKm: 1.2,
            evacuationTimeHours: 0.8,
            nearbyHospitals: ['AIIMS Guwahati Emergency Hospital (1.1km)'],
            roadStatus: 'Open',
            primaryRoad: 'NH-31 Elevated Bypass',
            rainfallMm: 85,
            waterLevelM: 0.0,
            factors: {
                historicalDisasters: 0,
                rainfallImpact: 18,
                elevationVulnerability: 8,
                populationDensity: 28,
                infrastructureVulnerability: 12,
                distanceToEmergencyServices: 15,
                roadAccessibility: 94
            },
            recommendedAction: 'NORTH REGION RELOCATION DESTINATION: AIIMS Trauma Beds & Relief Reception',
            targetRelocationCell: null
        },
        {
            id: '8761892507fffff',
            name: 'Narengi Hilltop Buffer',
            sector: 'East Cantonment Safe Highland',
            lat: 26.1700,
            lng: 91.8450,
            elevation: 142.0,
            baselineRisk: 10,
            currentRisk: 14,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 9800,
            vulnerablePopulation: {
                total: 1600,
                infants: 420,
                elderly: 640,
                disabled: 210,
                pregnant: 330
            },
            carryingCapacity: 42000,
            safeCapacityThreshold: 50000,
            capacityDeficit: -32200, // Surplus of 32,200
            nearestShelter: 'Army Cantonment Multi-Gymnasium Complex',
            shelterCapacity: 18000,
            shelterDistanceKm: 0.9,
            evacuationTimeHours: 0.7,
            nearbyHospitals: ['Military Hospital Narengi (1.4km)'],
            roadStatus: 'Open',
            primaryRoad: 'Cantonment Perimeter Expressway',
            rainfallMm: 90,
            waterLevelM: 0.0,
            factors: {
                historicalDisasters: 0,
                rainfallImpact: 16,
                elevationVulnerability: 6,
                populationDensity: 22,
                infrastructureVulnerability: 10,
                distanceToEmergencyServices: 18,
                roadAccessibility: 92
            },
            recommendedAction: 'MILITARY CO-ORD RELOCATION HUB: Heli-Pad & Field Kitchen Operating',
            targetRelocationCell: null
        },
        {
            id: '8761892509fffff',
            name: 'Gauhati University Ridge',
            sector: 'West Academic Safe Plateau',
            lat: 26.1600,
            lng: 91.6800,
            elevation: 96.0,
            baselineRisk: 16,
            currentRisk: 21,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 13200,
            vulnerablePopulation: {
                total: 2100,
                infants: 520,
                elderly: 820,
                disabled: 290,
                pregnant: 470
            },
            carryingCapacity: 38000,
            safeCapacityThreshold: 45000,
            capacityDeficit: -24800,
            nearestShelter: 'GU New Academic Concourse',
            shelterCapacity: 15000,
            shelterDistanceKm: 0.4,
            evacuationTimeHours: 0.5,
            nearbyHospitals: ['University Health Centre (0.3km)', 'Ayursundra Superspecialty (2.5km)'],
            roadStatus: 'Open',
            primaryRoad: 'University Ridge Spine Way',
            rainfallMm: 105,
            waterLevelM: 0.0,
            factors: {
                historicalDisasters: 0,
                rainfallImpact: 22,
                elevationVulnerability: 12,
                populationDensity: 32,
                infrastructureVulnerability: 14,
                distanceToEmergencyServices: 22,
                roadAccessibility: 95
            },
            recommendedAction: 'WEST CORRIDOR RELOCATION HUB: Student Hostels Converted to Evacuation Quarters',
            targetRelocationCell: null
        },

        // EXPANDED DISTRICT CELLS (Completing 24 high-resolution cells covering the river valley)
        {
            id: '8761892511fffff',
            name: 'Sonapur Agricultural Terrace',
            sector: 'East Rural Plateau',
            lat: 26.1100,
            lng: 91.9500,
            elevation: 105.0,
            baselineRisk: 15,
            currentRisk: 19,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 8900,
            vulnerablePopulation: { total: 1700, infants: 450, elderly: 710, disabled: 210, pregnant: 330 },
            carryingCapacity: 35000,
            safeCapacityThreshold: 40000,
            capacityDeficit: -26100,
            nearestShelter: 'Sonapur Rural Staging Depot',
            shelterCapacity: 12000,
            shelterDistanceKm: 1.5,
            evacuationTimeHours: 1.1,
            nearbyHospitals: ['Sonapur District Civil Hospital (2.0km)'],
            roadStatus: 'Open',
            primaryRoad: 'Asian Highway 1',
            rainfallMm: 95,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 1, rainfallImpact: 20, elevationVulnerability: 12, populationDensity: 20, infrastructureVulnerability: 18, distanceToEmergencyServices: 30, roadAccessibility: 90 },
            recommendedAction: 'Rural Agro-Shelter Depot Ready for Influx',
            targetRelocationCell: null
        },
        {
            id: '8761892513fffff',
            name: 'Kahilipara Hill Ridge',
            sector: 'South Ridge Sector',
            lat: 26.1380,
            lng: 91.7650,
            elevation: 110.0,
            baselineRisk: 22,
            currentRisk: 28,
            riskLevel: 'safe',
            hazardType: 'Landslide',
            population: 18600,
            vulnerablePopulation: { total: 3400, infants: 850, elderly: 1400, disabled: 450, pregnant: 700 },
            carryingCapacity: 32000,
            safeCapacityThreshold: 38000,
            capacityDeficit: -13400,
            nearestShelter: 'Special Task Force Police Academy',
            shelterCapacity: 10000,
            shelterDistanceKm: 0.8,
            evacuationTimeHours: 0.9,
            nearbyHospitals: ['Dispur Government Poly (2.1km)'],
            roadStatus: 'Open',
            primaryRoad: 'Kahilipara Hill Spine Road',
            rainfallMm: 120,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 1, rainfallImpact: 32, elevationVulnerability: 18, populationDensity: 48, infrastructureVulnerability: 22, distanceToEmergencyServices: 24, roadAccessibility: 88 },
            recommendedAction: 'High Elevation Refuge; Monitor Drainage',
            targetRelocationCell: null
        },
        {
            id: '8761892515fffff',
            name: 'Betkuchi Terminal Basin',
            sector: 'South Transport Corridor',
            lat: 26.1180,
            lng: 91.7300,
            elevation: 58.0,
            baselineRisk: 52,
            currentRisk: 69,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 24200,
            vulnerablePopulation: { total: 5700, infants: 1550, elderly: 2250, disabled: 740, pregnant: 1160 },
            carryingCapacity: 11000,
            safeCapacityThreshold: 22000,
            capacityDeficit: 13200,
            nearestShelter: 'ISBT Inter-State Terminal Mega Concourse',
            shelterCapacity: 8000,
            shelterDistanceKm: 0.9,
            evacuationTimeHours: 2.8,
            nearbyHospitals: ['Ayursundra Hospital (4.5km)'],
            roadStatus: 'Congested',
            primaryRoad: 'NH-27 Arterial Express',
            rainfallMm: 220,
            waterLevelM: 1.5,
            factors: { historicalDisasters: 5, rainfallImpact: 72, elevationVulnerability: 64, populationDensity: 82, infrastructureVulnerability: 68, distanceToEmergencyServices: 34, roadAccessibility: 62 },
            recommendedAction: 'Evacuate Terminal Perimeters; Route Evacuee Fleets South to Khanapara',
            targetRelocationCell: '8761892501fffff'
        },
        {
            id: '8761892517fffff',
            name: 'Deepor Beel Eco-Catchment',
            sector: 'Southwest Wetland Zone',
            lat: 26.1250,
            lng: 91.6500,
            elevation: 43.5, // Lowest elevation in the sector!
            baselineRisk: 82,
            currentRisk: 95,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 15800,
            vulnerablePopulation: { total: 5100, infants: 1600, elderly: 1950, disabled: 650, pregnant: 900 },
            carryingCapacity: 1200,
            safeCapacityThreshold: 12000,
            capacityDeficit: 14600,
            nearestShelter: 'Azara Railway High Ground Shelter',
            shelterCapacity: 4500,
            shelterDistanceKm: 3.2,
            evacuationTimeHours: 5.8,
            nearbyHospitals: ['Azara Primary Health Centre (2.8km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Deepor Ring Road',
            rainfallMm: 360,
            waterLevelM: 4.6,
            factors: { historicalDisasters: 12, rainfallImpact: 98, elevationVulnerability: 98, populationDensity: 74, infrastructureVulnerability: 95, distanceToEmergencyServices: 72, roadAccessibility: 12 },
            recommendedAction: 'Immediate Amphibious Rescue Operation (Priority 1) - Complete Inundation',
            targetRelocationCell: '8761892509fffff'
        },
        {
            id: '8761892519fffff',
            name: 'Azara Airport Corridor',
            sector: 'West Aviation Sector',
            lat: 26.1080,
            lng: 91.5950,
            elevation: 62.0,
            baselineRisk: 38,
            currentRisk: 46,
            riskLevel: 'moderate',
            hazardType: 'Cyclone',
            population: 17900,
            vulnerablePopulation: { total: 3900, infants: 980, elderly: 1550, disabled: 520, pregnant: 850 },
            carryingCapacity: 21000,
            safeCapacityThreshold: 26000,
            capacityDeficit: -3100,
            nearestShelter: 'LGBI Airport Hangar Shelter & Logistics Base',
            shelterCapacity: 12000,
            shelterDistanceKm: 1.8,
            evacuationTimeHours: 1.4,
            nearbyHospitals: ['Airforce Base Hospital (2.5km)'],
            roadStatus: 'Open',
            primaryRoad: 'Airport VIP Expressway',
            rainfallMm: 160,
            waterLevelM: 0.4,
            factors: { historicalDisasters: 3, rainfallImpact: 48, elevationVulnerability: 44, populationDensity: 52, infrastructureVulnerability: 40, distanceToEmergencyServices: 20, roadAccessibility: 90 },
            recommendedAction: 'Aviation Relief Airbridge Operating; Runway Dry',
            targetRelocationCell: '8761892509fffff'
        },
        {
            id: '8761892521fffff',
            name: 'Saraighat North Approach',
            sector: 'River Crossing North',
            lat: 26.2050,
            lng: 91.6850,
            elevation: 50.2,
            baselineRisk: 68,
            currentRisk: 84,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 21300,
            vulnerablePopulation: { total: 5600, infants: 1500, elderly: 2100, disabled: 800, pregnant: 1200 },
            carryingCapacity: 3400,
            safeCapacityThreshold: 19000,
            capacityDeficit: 17900,
            nearestShelter: 'Saraighat Engineering Complex',
            shelterCapacity: 5000,
            shelterDistanceKm: 2.2,
            evacuationTimeHours: 4.1,
            nearbyHospitals: ['Narayana Superspecialty (2.5km)'],
            roadStatus: 'Damaged',
            primaryRoad: 'Old Saraighat Bridge Approach',
            rainfallMm: 285,
            waterLevelM: 3.1,
            factors: { historicalDisasters: 7, rainfallImpact: 86, elevationVulnerability: 82, populationDensity: 80, infrastructureVulnerability: 88, distanceToEmergencyServices: 58, roadAccessibility: 30 },
            recommendedAction: 'Bridge Perimeter Heavy Vehicle Closure; Evacuate Riverside Settlements',
            targetRelocationCell: '8761892505fffff'
        },
        {
            id: '8761892523fffff',
            name: 'North Guwahati Heritage Reach',
            sector: 'North Riverbank Heritage Reach',
            lat: 26.2200,
            lng: 91.7450,
            elevation: 54.0,
            baselineRisk: 60,
            currentRisk: 76,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 18700,
            vulnerablePopulation: { total: 4700, infants: 1250, elderly: 1850, disabled: 620, pregnant: 980 },
            carryingCapacity: 7200,
            safeCapacityThreshold: 17000,
            capacityDeficit: 11500,
            nearestShelter: 'Doul Govinda High Ground Hall',
            shelterCapacity: 4500,
            shelterDistanceKm: 1.2,
            evacuationTimeHours: 3.1,
            nearbyHospitals: ['North Guwahati Civil Hospital (1.8km)'],
            roadStatus: 'Congested',
            primaryRoad: 'Heritage Riverway',
            rainfallMm: 245,
            waterLevelM: 2.1,
            factors: { historicalDisasters: 6, rainfallImpact: 78, elevationVulnerability: 70, populationDensity: 76, infrastructureVulnerability: 75, distanceToEmergencyServices: 62, roadAccessibility: 48 },
            recommendedAction: 'Suspend River Ferry Services; Evacuate Lowlands Northward',
            targetRelocationCell: '8761892505fffff'
        },
        {
            id: '8761892525fffff',
            name: 'Kalyanpur Flood Channel',
            sector: 'East Wetland Spur',
            lat: 26.1750,
            lng: 91.8200,
            elevation: 51.0,
            baselineRisk: 64,
            currentRisk: 79,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 25400,
            vulnerablePopulation: { total: 6600, infants: 1850, elderly: 2550, disabled: 880, pregnant: 1320 },
            carryingCapacity: 8500,
            safeCapacityThreshold: 23000,
            capacityDeficit: 16900,
            nearestShelter: 'Narengi High School Camp',
            shelterCapacity: 6000,
            shelterDistanceKm: 1.9,
            evacuationTimeHours: 3.6,
            nearbyHospitals: ['Military Hospital Narengi (3.1km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Bondamunda Channel Way',
            rainfallMm: 260,
            waterLevelM: 2.4,
            factors: { historicalDisasters: 6, rainfallImpact: 82, elevationVulnerability: 78, populationDensity: 84, infrastructureVulnerability: 80, distanceToEmergencyServices: 65, roadAccessibility: 40 },
            recommendedAction: 'Stage-2 Evacuation of Flood Bypass Zone to Narengi Ridge',
            targetRelocationCell: '8761892507fffff'
        },
        {
            id: '8761892527fffff',
            name: 'Bonda Lowland Agrarian Sector',
            sector: 'Far East Lowland',
            lat: 26.1900,
            lng: 91.8650,
            elevation: 48.0,
            baselineRisk: 71,
            currentRisk: 87,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 20100,
            vulnerablePopulation: { total: 5900, infants: 1700, elderly: 2300, disabled: 790, pregnant: 1110 },
            carryingCapacity: 3100,
            safeCapacityThreshold: 18000,
            capacityDeficit: 17000,
            nearestShelter: 'Bonda Model High School',
            shelterCapacity: 3500,
            shelterDistanceKm: 2.1,
            evacuationTimeHours: 4.4,
            nearbyHospitals: ['Civil Dispensary Bonda (2.4km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Panikhaiti Embankment Road',
            rainfallMm: 300,
            waterLevelM: 3.6,
            factors: { historicalDisasters: 8, rainfallImpact: 90, elevationVulnerability: 88, populationDensity: 78, infrastructureVulnerability: 86, distanceToEmergencyServices: 70, roadAccessibility: 22 },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1) via Inflatable Boats',
            targetRelocationCell: '8761892507fffff'
        },
        {
            id: '8761892529fffff',
            name: 'Panikhaiti River Bend',
            sector: 'Northeast Brahmaputra Bend',
            lat: 26.2150,
            lng: 91.8850,
            elevation: 47.5,
            baselineRisk: 76,
            currentRisk: 89,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 17500,
            vulnerablePopulation: { total: 5200, infants: 1500, elderly: 2050, disabled: 720, pregnant: 930 },
            carryingCapacity: 2800,
            safeCapacityThreshold: 16000,
            capacityDeficit: 14700,
            nearestShelter: 'Assam Down Town University High Ground Block',
            shelterCapacity: 7500,
            shelterDistanceKm: 1.8,
            evacuationTimeHours: 4.2,
            nearbyHospitals: ['Down Town Clinic (1.9km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Panikhaiti-Chandrapur Road',
            rainfallMm: 315,
            waterLevelM: 3.9,
            factors: { historicalDisasters: 9, rainfallImpact: 92, elevationVulnerability: 90, populationDensity: 75, infrastructureVulnerability: 88, distanceToEmergencyServices: 76, roadAccessibility: 20 },
            recommendedAction: 'Immediate Mandatory Evacuation (Priority 1) - High Current Warning',
            targetRelocationCell: '8761892507fffff'
        },
        {
            id: '8761892531fffff',
            name: 'Chandrapur Elevated Ridge',
            sector: 'Far Northeast Safe Ridge',
            lat: 26.2300,
            lng: 91.9300,
            elevation: 135.0,
            baselineRisk: 12,
            currentRisk: 16,
            riskLevel: 'safe',
            hazardType: 'Flood',
            population: 11200,
            vulnerablePopulation: { total: 2000, infants: 510, elderly: 780, disabled: 270, pregnant: 440 },
            carryingCapacity: 36000,
            safeCapacityThreshold: 42000,
            capacityDeficit: -24800,
            nearestShelter: 'Chandrapur Thermal Complex Relief Camp',
            shelterCapacity: 14000,
            shelterDistanceKm: 1.2,
            evacuationTimeHours: 0.6,
            nearbyHospitals: ['Chandrapur Community Health Center (1.0km)'],
            roadStatus: 'Open',
            primaryRoad: 'Chandrapur Ridge Way',
            rainfallMm: 95,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 0, rainfallImpact: 20, elevationVulnerability: 8, populationDensity: 25, infrastructureVulnerability: 16, distanceToEmergencyServices: 35, roadAccessibility: 91 },
            recommendedAction: 'East Safe Destination Buffer: Field Relief Kitchen Online',
            targetRelocationCell: null
        }
    ];

    // Road Networks connecting H3 cells
    const roadNetwork = [
        { id: 'ROAD-01', name: 'NH-27 Guwahati Bypass Expressway', fromCell: '8761892551fffff', toCell: '8761892501fffff', status: 'Open', lanes: 6, maxFlowPph: 8500, riskMultiplier: 1.0 },
        { id: 'ROAD-02', name: 'MG Embankment River Corridor', fromCell: '8761892543fffff', toCell: '8761892541fffff', status: 'Submerged', lanes: 4, maxFlowPph: 0, riskMultiplier: 4.8 },
        { id: 'ROAD-03', name: 'GS Road Central Elevated Spine', fromCell: '8761892555fffff', toCell: '8761892503fffff', status: 'Congested', lanes: 4, maxFlowPph: 3200, riskMultiplier: 1.6 },
        { id: 'ROAD-04', name: 'Khanapara Expressway Elevated Link', fromCell: '8761892503fffff', toCell: '8761892501fffff', status: 'Open', lanes: 6, maxFlowPph: 9000, riskMultiplier: 1.0 },
        { id: 'ROAD-05', name: 'Pandu-Jalukbari Relief Arterial', fromCell: '8761892543fffff', toCell: '8761892551fffff', status: 'Damaged', lanes: 2, maxFlowPph: 800, riskMultiplier: 3.2 },
        { id: 'ROAD-06', name: 'Saraighat New Bridge Corridor', fromCell: '8761892551fffff', toCell: '8761892545fffff', status: 'Open', lanes: 4, maxFlowPph: 6000, riskMultiplier: 1.2 },
        { id: 'ROAD-07', name: 'North Bank AIIMS Highway (NH-31)', fromCell: '8761892545fffff', toCell: '8761892505fffff', status: 'Open', lanes: 4, maxFlowPph: 7200, riskMultiplier: 1.0 },
        { id: 'ROAD-08', name: 'Fatasil Sluice Relief Bypass', fromCell: '8761892557fffff', toCell: '8761892515fffff', status: 'Submerged', lanes: 2, maxFlowPph: 0, riskMultiplier: 5.0 },
        { id: 'ROAD-09', name: 'ISBT South Connector', fromCell: '8761892515fffff', toCell: '8761892501fffff', status: 'Open', lanes: 4, maxFlowPph: 5500, riskMultiplier: 1.1 },
        { id: 'ROAD-10', name: 'Noonmati-Narengi Ridge Link', fromCell: '8761892549fffff', toCell: '8761892507fffff', status: 'Open', lanes: 2, maxFlowPph: 2400, riskMultiplier: 1.3 }
    ];

    // Dedicated Emergency Shelters
    const shelters = [
        { id: 'SH-01', name: 'Khanapara Veterinary Mega Relief Hub', cellId: '8761892501fffff', capacity: 28000, currentOccupancy: 8400, availableCapacity: 19600, status: 'Active Reception', foodWaterDays: 14, medicalUnits: 12, powerBackup: 'Dual 250kVA GenSet + Solar Grid' },
        { id: 'SH-02', name: 'Assam Secretariat High-Ground Pavilion', cellId: '8761892503fffff', capacity: 22000, currentOccupancy: 6100, availableCapacity: 15900, status: 'Active Reception', foodWaterDays: 18, medicalUnits: 10, powerBackup: 'Government Dedicated Line + GenSet' },
        { id: 'SH-03', name: 'AIIMS Guwahati Super Campus Shelter', cellId: '8761892505fffff', capacity: 25000, currentOccupancy: 4200, availableCapacity: 20800, status: 'Active Reception', foodWaterDays: 21, medicalUnits: 25, powerBackup: 'Hospital Tri-Redundant Power' },
        { id: 'SH-04', name: 'Army Cantonment Multi-Gymnasium', cellId: '8761892507fffff', capacity: 18000, currentOccupancy: 3900, availableCapacity: 14100, status: 'Active Reception', foodWaterDays: 30, medicalUnits: 16, powerBackup: 'Military Independent Substation' },
        { id: 'SH-05', name: 'Gauhati University New Academic Concourse', cellId: '8761892509fffff', capacity: 15000, currentOccupancy: 5200, availableCapacity: 9800, status: 'Active Reception', foodWaterDays: 10, medicalUnits: 8, powerBackup: 'Solar Grid 120kW + GenSet' },
        { id: 'SH-06', name: 'Sarujasai Stadium Indoor Pavilion', cellId: '8761892563fffff', capacity: 12000, currentOccupancy: 2800, availableCapacity: 9200, status: 'Active Reception', foodWaterDays: 12, medicalUnits: 6, powerBackup: 'High-power Diesel GenSet' },
        { id: 'SH-07', name: 'Cotton University Multi-Story Complex', cellId: '8761892541fffff', capacity: 7500, currentOccupancy: 7400, availableCapacity: 100, status: 'AT CAPACITY BREACH', foodWaterDays: 3, medicalUnits: 4, powerBackup: 'Battery Inverter (Low)' },
        { id: 'SH-08', name: 'Kamrup Central Relief High School', cellId: '8761892543fffff', capacity: 5200, currentOccupancy: 5200, availableCapacity: 0, status: 'COMPROMISED (Water Surrounding)', foodWaterDays: 2, medicalUnits: 2, powerBackup: 'Submerged / Offline' }
    ];

    // Major Hospitals & Medical Facilities
    const hospitals = [
        { id: 'HOSP-01', name: 'Guwahati Medical College & Hospital (GMCH)', cellId: '8761892553fffff', beds: 1850, icuBeds: 210, availableIcu: 38, traumaCare: 'Level 1 Trauma', status: 'Operational (High Load)', lat: 26.158, lng: 91.772 },
        { id: 'HOSP-02', name: 'AIIMS Guwahati Super Specialty Hospital', cellId: '8761892505fffff', beds: 1200, icuBeds: 180, availableIcu: 84, traumaCare: 'Level 1 Trauma', status: 'Optimal / Safe Zone', lat: 26.262, lng: 91.708 },
        { id: 'HOSP-03', name: 'Narayana Superspeciality North Hospital', cellId: '8761892545fffff', beds: 450, icuBeds: 65, availableIcu: 12, traumaCare: 'Level 2 Trauma', status: 'Flooding Perimeter Watch', lat: 26.208, lng: 91.674 },
        { id: 'HOSP-04', name: 'GNRC Hospitals Six Mile', cellId: '8761892561fffff', beds: 500, icuBeds: 85, availableIcu: 24, traumaCare: 'Level 1 Trauma', status: 'Operational / Safe Corridor', lat: 26.138, lng: 91.812 },
        { id: 'HOSP-05', name: 'Military Hospital Narengi Cantonment', cellId: '8761892507fffff', beds: 650, icuBeds: 90, availableIcu: 46, traumaCare: 'Level 1 Military Field', status: 'Optimal / Safe High Ground', lat: 26.172, lng: 91.848 },
        { id: 'HOSP-06', name: 'Dispur Polyclinic & Hospital', cellId: '8761892503fffff', beds: 380, icuBeds: 50, availableIcu: 19, traumaCare: 'Level 2 Trauma', status: 'Operational', lat: 26.146, lng: 91.794 },
        { id: 'HOSP-07', name: 'Mahendra Mohan Choudhury Hospital (MMCH)', cellId: '8761892541fffff', beds: 320, icuBeds: 35, availableIcu: 0, traumaCare: 'Level 2 Trauma', status: 'EVACUATION IN PROGRESS (Basement Inundated)', lat: 26.192, lng: 91.750 }
    ];

    // Emergency Response Teams & Fleet Inventory
    const emergencyResources = [
        { id: 'RES-01', type: 'NDRF Battalion 01', category: 'Water Amphibious Rescue', units: 18, boats: 36, personnel: 180, deployedCell: '8761892543fffff', status: 'Active Rescue', task: 'Evacuating Pandu Ghat low-lying settlements' },
        { id: 'RES-02', type: 'NDRF Battalion 02', category: 'Water Amphibious Rescue', units: 14, boats: 28, personnel: 140, deployedCell: '8761892517fffff', status: 'Active Rescue', task: 'Deepor Beel wetland rescue operations' },
        { id: 'RES-03', type: 'SDRF Rapid Reaction Unit', category: 'Urban Search & Rescue', units: 12, boats: 16, personnel: 96, deployedCell: '8761892557fffff', status: 'Active Rescue', task: 'Fatasil slum mudflow & extraction' },
        { id: 'RES-04', type: 'Indian Army 51 Sub-Area Task Force', category: 'Heavy Engineering & Amphibian', units: 8, helo: 4, personnel: 240, deployedCell: '8761892507fffff', status: 'Staged / Deploying', task: 'Operating Narengi Airbridge & heavy troop transport' },
        { id: 'RES-05', type: 'State Transport Evacuation Fleet (ASTC)', category: 'Ground Transport Fleet', units: 120, buses: 120, personnel: 180, deployedCell: '8761892501fffff', status: 'Active Transit', task: 'Running shuttle corridors from transit points to Khanapara' },
        { id: 'RES-06', type: '108 Advanced Life Support (ALS) Ambulance Squad', category: 'Medical Mobile Care', units: 48, ambulances: 48, personnel: 96, deployedCell: '8761892503fffff', status: 'Dispatched', task: 'Hospital evacuation shuttling critical care patients' },
        { id: 'RES-07', type: 'Civil Defence & Red Cross First Aid Core', category: 'Shelter Support & Logistics', units: 22, kitchens: 12, personnel: 320, deployedCell: '8761892501fffff', status: 'Active Food/Water', task: 'Serving 45,000 cooked meals per day at Khanapara' },
        { id: 'RES-08', type: 'Central Water Commission (CWC) Sensor Unit', category: 'Hydrological Monitoring', units: 8, sensors: 16, personnel: 16, deployedCell: '8761892541fffff', status: 'Continuous Telemetry', task: 'Real-time telemetry on river surge and embankment stress' }
    ];

    // Historical Disasters in the Sector
    const historicalDisasters = [
        {
            year: 2024,
            name: 'Cyclone Remal Inflow & Cloudburst',
            type: 'Flash Flood & Embankment Erosion',
            affectedPopulation: 142000,
            criticalCellsBreached: 8,
            peakRainfallMm: 310,
            evacuationTotal: 48500,
            relocationTotal: 34200,
            maxCarryingCapacityDeficit: 62000,
            durationDays: 6,
            keyLearning: 'Embankment failure along MG Road necessitated pre-designated high-ground safe corridors.'
        },
        {
            year: 2023,
            name: 'Brahmaputra Severe Monsoon Surge',
            type: 'Riverine Flood',
            affectedPopulation: 185000,
            criticalCellsBreached: 11,
            peakRainfallMm: 345,
            evacuationTotal: 62000,
            relocationTotal: 45000,
            maxCarryingCapacityDeficit: 88000,
            durationDays: 9,
            keyLearning: 'Khanapara ridge proved to be the single most resilient relocation node; shelter capacity increased.'
        },
        {
            year: 2022,
            name: 'Assam Mega Inundation & Landslides',
            type: 'Compound Flood & Hillside Slips',
            affectedPopulation: 240000,
            criticalCellsBreached: 14,
            peakRainfallMm: 390,
            evacuationTotal: 84000,
            relocationTotal: 61000,
            maxCarryingCapacityDeficit: 112000,
            durationDays: 14,
            keyLearning: 'Identified need for dynamic spatial indexing (H3) to compute localized carrying capacity deficits.'
        },
        {
            year: 2020,
            name: 'Super Cyclone Amphan Rain Band',
            type: 'Urban Deluge & River Inundation',
            affectedPopulation: 128000,
            criticalCellsBreached: 7,
            peakRainfallMm: 280,
            evacuationTotal: 39000,
            relocationTotal: 27500,
            maxCarryingCapacityDeficit: 54000,
            durationDays: 5,
            keyLearning: 'Pandu Ghat and Deepor Beel cells consistently exhibit carrying capacity collapse within 6 hours.'
        },
        {
            year: 2018,
            name: 'Great Brahmaputra Basin Inundation',
            type: 'Catastrophic Basin Breach',
            affectedPopulation: 320000,
            criticalCellsBreached: 18,
            peakRainfallMm: 425,
            evacuationTotal: 110000,
            relocationTotal: 78000,
            maxCarryingCapacityDeficit: 148000,
            durationDays: 18,
            keyLearning: 'Catalyzed development of SIH26191 intelligent carrying capacity relocation decision system.'
        }
    ];

    // Relocation Matching Matrix (Automated Recommendations)
    const relocationAllocations = [
        {
            sourceCellId: '8761892543fffff', // Pandu Ghat (Critical, Deficit: 23,900)
            targetCellId: '8761892501fffff', // Khanapara Safe Ridge (Surplus: 50,800)
            allocatedPopulation: 23900,
            distanceKm: 14.8,
            travelTimeMinutes: 38,
            corridorStatus: 'NH-27 Open Bypass Corridor',
            medicalSupport: 'Army Base Hospital & GNRC Medical',
            priority: 'P1 - Immediate',
            transitMode: 'Amphibious Ferry to High Ground + ASTC Bus Fleet'
        },
        {
            sourceCellId: '8761892541fffff', // Uzan Bazar (Critical, Deficit: 27,900)
            targetCellId: '8761892503fffff', // Dispur Capital Ridge (Surplus: 35,900)
            allocatedPopulation: 27900,
            distanceKm: 7.2,
            travelTimeMinutes: 24,
            corridorStatus: 'Elevated Capitol Corridor',
            medicalSupport: 'Dispur Government Hospital & Clinic',
            priority: 'P1 - Immediate',
            transitMode: 'ASTC Rapid Bus Shuttle'
        },
        {
            sourceCellId: '8761892545fffff', // Amingaon Industrial (Critical, Deficit: 19,000)
            targetCellId: '8761892505fffff', // Changsari AIIMS Safe Zone (Surplus: 36,500)
            allocatedPopulation: 19000,
            distanceKm: 8.5,
            travelTimeMinutes: 20,
            corridorStatus: 'NH-31 North Elevated Bypass',
            medicalSupport: 'AIIMS Guwahati Super Specialty Trauma Unit',
            priority: 'P1 - Immediate',
            transitMode: 'North Bank Bus & Heavy Truck Convoy'
        },
        {
            sourceCellId: '8761892547fffff', // Bharalumukh (Critical, Deficit: 36,100)
            targetCellId: '8761892501fffff', // Khanapara Safe Ridge
            allocatedPopulation: 26900,
            distanceKm: 12.5,
            travelTimeMinutes: 32,
            corridorStatus: 'South Arterial Highway 27',
            medicalSupport: 'Guwahati Medical College & GNRC',
            priority: 'P1 - Immediate',
            transitMode: 'NDRF Inflatable Boats to Staging Hub + Bus Fleet'
        },
        {
            sourceCellId: '8761892557fffff', // Fatasil Slum (Critical, Deficit: 25,300)
            targetCellId: '8761892509fffff', // Gauhati University Ridge (Surplus: 24,800)
            allocatedPopulation: 18500,
            distanceKm: 6.4,
            travelTimeMinutes: 18,
            corridorStatus: 'University Ridge Spine Way',
            medicalSupport: 'Ayursundra Superspecialty & GU Health Center',
            priority: 'P1 - Immediate',
            transitMode: '4x4 Military Heavy All-Terrain Transport'
        },
        {
            sourceCellId: '8761892517fffff', // Deepor Beel (Critical, Deficit: 14,600)
            targetCellId: '8761892509fffff', // Gauhati University Ridge
            allocatedPopulation: 6300,
            distanceKm: 5.2,
            travelTimeMinutes: 15,
            corridorStatus: 'Airport Bypass Spur',
            medicalSupport: 'Azara Primary Health Unit',
            priority: 'P1 - Life Threat',
            transitMode: 'NDRF Powerboats & Airforce Rotary Extraction'
        },
        {
            sourceCellId: '8761892527fffff', // Bonda Lowland (Critical, Deficit: 17,000)
            targetCellId: '8761892507fffff', // Narengi Hilltop Buffer (Surplus: 32,200)
            allocatedPopulation: 17000,
            distanceKm: 4.8,
            travelTimeMinutes: 14,
            corridorStatus: 'Cantonment Perimeter Expressway',
            medicalSupport: 'Military Hospital Narengi',
            priority: 'P1 - Immediate',
            transitMode: 'Army Transport Convoys'
        }
    ];

    return {
        h3Cells,
        roadNetwork,
        shelters,
        hospitals,
        emergencyResources,
        historicalDisasters,
        relocationAllocations
    };
})();
