/**
 * SIH26191 - MHA/NDMA Disaster Command System
 * Realistic GIS & H3 Hexagonal Cell Dataset for MANALI · ROHTANG CORRIDOR (Beas River Basin, Himachal Pradesh)
 * Focus: Palchan - Bahang - Old Manali - Manali Mall Core - Aleo - Vashisht - Solang - Rohtang Pass
 */

window.DISASTER_DATA = (function() {
    // 24 H3 Hexagonal Cells across the vulnerable Manali Beas Basin & High-Ground Relocation Ridges
    const h3Cells = [
        // CRITICAL RED ZONES (Active Inundation & Cloudburst Surge along Beas Valley Floor)
        {
            id: '892834d2d2bffff', // Exact hazard cell from user Manali H3 geofence snippet
            name: 'Old Manali Bridge & Curve Sector',
            sector: 'Upper Beas River Gorge Reach',
            lat: 32.2432,
            lng: 77.1935,
            elevation: 2050.0,
            baselineRisk: 88,
            currentRisk: 96,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 14200,
            vulnerablePopulation: { total: 4100, infants: 1100, elderly: 1650, disabled: 520, pregnant: 830 },
            carryingCapacity: 950,
            safeCapacityThreshold: 12500,
            capacityDeficit: 13250,
            nearestShelter: 'ABVIMAS Mountaineering Complex, Manali',
            shelterCapacity: 30000,
            shelterDistanceKm: 1.8,
            evacuationTimeHours: 1.5,
            nearbyHospitals: ['Civil Hospital Manali (Left Bank)', 'Mission Hospital Manali (Old Manali)'],
            roadStatus: 'Submerged',
            primaryRoad: 'NH-3 Beas Corridor (Submerged at Mile 14 Curve)',
            rainfallMm: 360,
            waterLevelM: 4.8,
            factors: { historicalDisasters: 9, rainfallImpact: 98, elevationVulnerability: 94, populationDensity: 82, infrastructureVulnerability: 96, distanceToEmergencyServices: 45, roadAccessibility: 12 },
            recommendedAction: 'Immediate Mandatory Evacuation via ABVIMAS High Ridge Bypass',
            targetRelocationCell: '892834d2d03ffff' // ABVIMAS High Campus
        },
        {
            id: '892834d2d37ffff', // Exact second hazard cell from user snippet
            name: 'Beas Riverbed Lowland Core',
            sector: 'Central Manali Commercial Basin',
            lat: 32.2410,
            lng: 77.1905,
            elevation: 2020.0,
            baselineRisk: 84,
            currentRisk: 94,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 24800,
            vulnerablePopulation: { total: 7200, infants: 2100, elderly: 2850, disabled: 980, pregnant: 1270 },
            carryingCapacity: 2100,
            safeCapacityThreshold: 21000,
            capacityDeficit: 22700,
            nearestShelter: 'Manali Mall Road Municipal Town Hall (AT CAPACITY)',
            shelterCapacity: 4000,
            shelterDistanceKm: 0.6,
            evacuationTimeHours: 2.2,
            nearbyHospitals: ['Civil Hospital Manali (Water Perimeter Watch)', 'Regional Hospital Kullu (38km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Old Manali Wooden Bridge Approach (Submerged)',
            rainfallMm: 340,
            waterLevelM: 4.5,
            factors: { historicalDisasters: 8, rainfallImpact: 94, elevationVulnerability: 96, populationDensity: 94, infrastructureVulnerability: 92, distanceToEmergencyServices: 50, roadAccessibility: 15 },
            recommendedAction: 'Mandatory Evacuation (Priority 1) via Atal Tunnel High Corridor',
            targetRelocationCell: '892834d2d01ffff' // Atal Tunnel South Portal Safe Complex
        },
        {
            id: '892834d2d3fffff', // Exact third hazard cell from user snippet
            name: 'Bahang Inundation Embankment',
            sector: 'Mid-Beas Fluvial Meander Reach',
            lat: 32.2580,
            lng: 77.1840,
            elevation: 2080.0,
            baselineRisk: 80,
            currentRisk: 92,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 18600,
            vulnerablePopulation: { total: 5300, infants: 1450, elderly: 2100, disabled: 720, pregnant: 1030 },
            carryingCapacity: 1600,
            safeCapacityThreshold: 16000,
            capacityDeficit: 17000,
            nearestShelter: 'Vashisht Higher Ground Primary Relief Hub',
            shelterCapacity: 18000,
            shelterDistanceKm: 2.4,
            evacuationTimeHours: 2.8,
            nearbyHospitals: ['Civil Hospital Manali (4km)', 'Mission Hospital Manali (3.5km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'NH-3 Bahang Section (Severed by River Cutting)',
            rainfallMm: 320,
            waterLevelM: 4.2,
            factors: { historicalDisasters: 8, rainfallImpact: 92, elevationVulnerability: 92, populationDensity: 86, infrastructureVulnerability: 90, distanceToEmergencyServices: 55, roadAccessibility: 20 },
            recommendedAction: 'Immediate Evacuation via Vashisht Thermal High Ridge',
            targetRelocationCell: '892834d2d05ffff' // Vashisht Thermal High Ridge
        },
        {
            id: '892834d2d27ffff',
            name: 'Palchan Cloudburst Confluence',
            sector: 'Solang-Beas Confluence Throat',
            lat: 32.2850,
            lng: 77.1720,
            elevation: 2210.0,
            baselineRisk: 86,
            currentRisk: 95,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 11500,
            vulnerablePopulation: { total: 3200, infants: 850, elderly: 1300, disabled: 410, pregnant: 640 },
            carryingCapacity: 800,
            safeCapacityThreshold: 10000,
            capacityDeficit: 10700,
            nearestShelter: 'Solang Alpine Relief Hub & Complex',
            shelterCapacity: 25000,
            shelterDistanceKm: 3.2,
            evacuationTimeHours: 3.1,
            nearbyHospitals: ['Palchan Emergency Post (Inoperative)', 'Civil Hospital Manali (8km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Palchan-Solang Valley Bridge (Embankment Loss)',
            rainfallMm: 370,
            waterLevelM: 4.9,
            factors: { historicalDisasters: 9, rainfallImpact: 96, elevationVulnerability: 95, populationDensity: 70, infrastructureVulnerability: 94, distanceToEmergencyServices: 68, roadAccessibility: 14 },
            recommendedAction: 'Priority 1 Evacuation to Solang Alpine High Plateau',
            targetRelocationCell: '892834d2d07ffff' // Solang High Alpine Plateau
        },
        {
            id: '892834d2d2fffff',
            name: 'Solang Nullah Surge Reach',
            sector: 'Solang Glacial Stream Inundation Corridor',
            lat: 32.3150,
            lng: 77.1550,
            elevation: 2480.0,
            baselineRisk: 76,
            currentRisk: 88,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 9200,
            vulnerablePopulation: { total: 2600, infants: 680, elderly: 1050, disabled: 340, pregnant: 530 },
            carryingCapacity: 1100,
            safeCapacityThreshold: 8500,
            capacityDeficit: 8100,
            nearestShelter: 'Solang High Alpine Logistic Hub',
            shelterCapacity: 25000,
            shelterDistanceKm: 1.5,
            evacuationTimeHours: 1.8,
            nearbyHospitals: ['Solang Alpine Dispensary', 'Civil Hospital Manali (14km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'Solang Valley Floor Access Road (Debris Blockage)',
            rainfallMm: 310,
            waterLevelM: 3.8,
            factors: { historicalDisasters: 7, rainfallImpact: 88, elevationVulnerability: 90, populationDensity: 65, infrastructureVulnerability: 86, distanceToEmergencyServices: 60, roadAccessibility: 22 },
            recommendedAction: 'Immediate Ascent to Solang High Alpine Plateau',
            targetRelocationCell: '892834d2d07ffff'
        },
        {
            id: '892834d2d33ffff',
            name: 'Aleo - Manali Highway Riverside',
            sector: 'Lower Manali Beas Basin',
            lat: 32.2300,
            lng: 77.1950,
            elevation: 1980.0,
            baselineRisk: 78,
            currentRisk: 90,
            riskLevel: 'critical',
            hazardType: 'Flood',
            population: 17500,
            vulnerablePopulation: { total: 4900, infants: 1350, elderly: 1980, disabled: 640, pregnant: 930 },
            carryingCapacity: 1800,
            safeCapacityThreshold: 15500,
            capacityDeficit: 15700,
            nearestShelter: 'ABVIMAS High Campus (Manali Ridge)',
            shelterCapacity: 30000,
            shelterDistanceKm: 2.1,
            evacuationTimeHours: 2.4,
            nearbyHospitals: ['Civil Hospital Manali (1.8km)', 'Lady Willingdon Hospital (2.5km)'],
            roadStatus: 'Submerged',
            primaryRoad: 'NH-3 Aleo Riverbank Highway (Water Inundation)',
            rainfallMm: 330,
            waterLevelM: 4.0,
            factors: { historicalDisasters: 8, rainfallImpact: 90, elevationVulnerability: 94, populationDensity: 88, infrastructureVulnerability: 88, distanceToEmergencyServices: 40, roadAccessibility: 25 },
            recommendedAction: 'Relocation to ABVIMAS High Mountaineering Campus',
            targetRelocationCell: '892834d2d03ffff'
        },
        {
            id: '892834d2d1bffff',
            name: 'Marhi Landslide Chute (Rohtang Highway)',
            sector: 'Upper Rohtang Pass Alpine Incline',
            lat: 32.3480,
            lng: 77.2150,
            elevation: 3320.0,
            baselineRisk: 82,
            currentRisk: 89,
            riskLevel: 'critical',
            hazardType: 'Landslide',
            population: 6800,
            vulnerablePopulation: { total: 1900, infants: 480, elderly: 740, disabled: 260, pregnant: 420 },
            carryingCapacity: 600,
            safeCapacityThreshold: 6000,
            capacityDeficit: 6200,
            nearestShelter: 'Atal Tunnel South Portal Logistics Complex',
            shelterCapacity: 38000,
            shelterDistanceKm: 7.5,
            evacuationTimeHours: 4.2,
            nearbyHospitals: ['BRO Project Deepak Field Station', 'Manali Civil Hospital (28km)'],
            roadStatus: 'Damaged',
            primaryRoad: 'Rohtang Pass Highway (NH-3 Old) - Severe Rockfall',
            rainfallMm: 290,
            waterLevelM: 3.5,
            factors: { historicalDisasters: 9, rainfallImpact: 86, elevationVulnerability: 96, populationDensity: 52, infrastructureVulnerability: 95, distanceToEmergencyServices: 85, roadAccessibility: 10 },
            recommendedAction: 'Convoy Relocation through Atal Tunnel South Portal Hub',
            targetRelocationCell: '892834d2d01ffff'
        },

        // ORANGE ALERT ZONES (High Risk / Pre-Monsoon Staging / Severe Toe Cutting)
        {
            id: '892834d2d1fffff',
            name: 'Kothi Gorge Flank',
            sector: 'Upper Beas Gorge Terrace',
            lat: 32.3020,
            lng: 77.1850,
            elevation: 2520.0,
            baselineRisk: 68,
            currentRisk: 78,
            riskLevel: 'orange',
            hazardType: 'Landslide',
            population: 8400,
            vulnerablePopulation: { total: 2350, infants: 620, elderly: 940, disabled: 310, pregnant: 480 },
            carryingCapacity: 3500,
            safeCapacityThreshold: 9000,
            capacityDeficit: 4900,
            nearestShelter: 'Palchan High Staging Shelter',
            shelterCapacity: 12000,
            shelterDistanceKm: 2.2,
            evacuationTimeHours: 2.6,
            nearbyHospitals: ['Kothi Primary Health Subcentre', 'Civil Hospital Manali (12km)'],
            roadStatus: 'Congested',
            primaryRoad: 'Palchan-Kothi Ridge Connector Road',
            rainfallMm: 280,
            waterLevelM: 1.8,
            factors: { historicalDisasters: 6, rainfallImpact: 78, elevationVulnerability: 82, populationDensity: 58, infrastructureVulnerability: 74, distanceToEmergencyServices: 65, roadAccessibility: 52 },
            recommendedAction: 'Stage-2 Evacuation Pre-emption to Solang Plateau',
            targetRelocationCell: '892834d2d07ffff'
        },
        {
            id: '892834d2d3bffff',
            name: 'Nehru Kund Vulnerable Meander',
            sector: 'Mid-Beas Alluvial Terrace',
            lat: 32.2700,
            lng: 77.1810,
            elevation: 2160.0,
            baselineRisk: 65,
            currentRisk: 74,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 10800,
            vulnerablePopulation: { total: 3050, infants: 820, elderly: 1210, disabled: 410, pregnant: 610 },
            carryingCapacity: 4800,
            safeCapacityThreshold: 11500,
            capacityDeficit: 6000,
            nearestShelter: 'Vashisht Higher Ground Relief Hub',
            shelterCapacity: 18000,
            shelterDistanceKm: 2.8,
            evacuationTimeHours: 2.2,
            nearbyHospitals: ['Civil Hospital Manali (5.5km)'],
            roadStatus: 'Congested',
            primaryRoad: 'NH-3 Nehru Kund Stretch (Partial Submergence)',
            rainfallMm: 270,
            waterLevelM: 1.6,
            factors: { historicalDisasters: 6, rainfallImpact: 75, elevationVulnerability: 80, populationDensity: 66, infrastructureVulnerability: 70, distanceToEmergencyServices: 45, roadAccessibility: 55 },
            recommendedAction: 'Staged Evacuation via Vashisht High Bypass',
            targetRelocationCell: '892834d2d05ffff'
        },
        {
            id: '892834d2d0bffff',
            name: 'Gulaba Avalanche & Slump Zone',
            sector: 'Rohtang Approach Incline',
            lat: 32.3250,
            lng: 77.2020,
            elevation: 2950.0,
            baselineRisk: 67,
            currentRisk: 76,
            riskLevel: 'orange',
            hazardType: 'Landslide',
            population: 5900,
            vulnerablePopulation: { total: 1650, infants: 420, elderly: 650, disabled: 220, pregnant: 360 },
            carryingCapacity: 2400,
            safeCapacityThreshold: 6500,
            capacityDeficit: 3500,
            nearestShelter: 'Atal Tunnel South Complex Transit Camp',
            shelterCapacity: 38000,
            shelterDistanceKm: 6.2,
            evacuationTimeHours: 3.4,
            nearbyHospitals: ['BRO Field First Aid Post Gulaba'],
            roadStatus: 'Damaged',
            primaryRoad: 'Gulaba Barrier Highway (Debris Flow)',
            rainfallMm: 260,
            waterLevelM: 1.2,
            factors: { historicalDisasters: 7, rainfallImpact: 76, elevationVulnerability: 85, populationDensity: 46, infrastructureVulnerability: 78, distanceToEmergencyServices: 75, roadAccessibility: 40 },
            recommendedAction: 'Stage-2 Pre-emptive Relocation to Atal Tunnel Complex',
            targetRelocationCell: '892834d2d01ffff'
        },
        {
            id: '892834d2d47ffff',
            name: 'Klash - 15 Mile Meander Reach',
            sector: 'South Manali River Meander Basin',
            lat: 32.2100,
            lng: 77.1980,
            elevation: 1920.0,
            baselineRisk: 62,
            currentRisk: 70,
            riskLevel: 'orange',
            hazardType: 'Flood',
            population: 13400,
            vulnerablePopulation: { total: 3750, infants: 1020, elderly: 1510, disabled: 490, pregnant: 730 },
            carryingCapacity: 6200,
            safeCapacityThreshold: 14000,
            capacityDeficit: 7200,
            nearestShelter: 'Naggar Heritage Government Complex',
            shelterCapacity: 22000,
            shelterDistanceKm: 6.5,
            evacuationTimeHours: 2.5,
            nearbyHospitals: ['Lady Willingdon Hospital (4.5km)', 'Kullu Hospital (30km)'],
            roadStatus: 'Congested',
            primaryRoad: 'NH-3 Right Bank Highway (Water Logging)',
            rainfallMm: 250,
            waterLevelM: 1.5,
            factors: { historicalDisasters: 5, rainfallImpact: 72, elevationVulnerability: 78, populationDensity: 74, infrastructureVulnerability: 68, distanceToEmergencyServices: 50, roadAccessibility: 58 },
            recommendedAction: 'Planned Relocation to Naggar Heritage Plateau',
            targetRelocationCell: '892834d2d09ffff'
        },
        {
            id: '892834d2d4fffff',
            name: 'Prini Left Bank Slope Flank',
            sector: 'Left Bank Foothill Incline',
            lat: 32.2220,
            lng: 77.2050,
            elevation: 2060.0,
            baselineRisk: 58,
            currentRisk: 66,
            riskLevel: 'orange',
            hazardType: 'Landslide',
            population: 11200,
            vulnerablePopulation: { total: 3100, infants: 850, elderly: 1250, disabled: 410, pregnant: 590 },
            carryingCapacity: 5500,
            safeCapacityThreshold: 12000,
            capacityDeficit: 5700,
            nearestShelter: 'ABVIMAS High Mountain Campus',
            shelterCapacity: 30000,
            shelterDistanceKm: 3.4,
            evacuationTimeHours: 2.1,
            nearbyHospitals: ['Civil Hospital Manali (3km)'],
            roadStatus: 'Congested',
            primaryRoad: 'Left Bank Alternate Highway (Active Slump)',
            rainfallMm: 240,
            waterLevelM: 1.0,
            factors: { historicalDisasters: 5, rainfallImpact: 68, elevationVulnerability: 74, populationDensity: 68, infrastructureVulnerability: 64, distanceToEmergencyServices: 35, roadAccessibility: 62 },
            recommendedAction: 'Staged Evacuation to ABVIMAS High Campus',
            targetRelocationCell: '892834d2d03ffff'
        },

        // YELLOW WATCH ZONES (Moderate Risk / River Terraces & Slope Buffer)
        {
            id: '892834d2d53ffff',
            name: 'Jagatsukh Ancient River Terrace',
            sector: 'Left Bank Historic Terrace',
            lat: 32.1950,
            lng: 77.2050,
            elevation: 2010.0,
            baselineRisk: 46,
            currentRisk: 54,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 14500,
            vulnerablePopulation: { total: 4050, infants: 1100, elderly: 1620, disabled: 530, pregnant: 800 },
            carryingCapacity: 15000,
            safeCapacityThreshold: 17000,
            capacityDeficit: 0,
            nearestShelter: 'Jagatsukh Community Relief Centre',
            shelterCapacity: 8000,
            shelterDistanceKm: 1.2,
            evacuationTimeHours: 1.6,
            nearbyHospitals: ['Jagatsukh Primary Health Centre'],
            roadStatus: 'Open',
            primaryRoad: 'Jagatsukh Left Bank Road (Open)',
            rainfallMm: 200,
            waterLevelM: 0.4,
            factors: { historicalDisasters: 4, rainfallImpact: 54, elevationVulnerability: 58, populationDensity: 65, infrastructureVulnerability: 50, distanceToEmergencyServices: 40, roadAccessibility: 80 }
        },
        {
            id: '892834d2d57ffff',
            name: 'Haripur Stream Terrace',
            sector: 'Mid-Kullu Fluvial Terrace',
            lat: 32.1700,
            lng: 77.1920,
            elevation: 1880.0,
            baselineRisk: 42,
            currentRisk: 48,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 12800,
            vulnerablePopulation: { total: 3550, infants: 950, elderly: 1420, disabled: 470, pregnant: 710 },
            carryingCapacity: 13500,
            safeCapacityThreshold: 15000,
            capacityDeficit: 0,
            nearestShelter: 'Haripur Government School Shelter',
            shelterCapacity: 6500,
            shelterDistanceKm: 1.1,
            evacuationTimeHours: 1.4,
            nearbyHospitals: ['Haripur Civil Dispensary'],
            roadStatus: 'Open',
            primaryRoad: 'NH-3 Right Bank Bypass',
            rainfallMm: 190,
            waterLevelM: 0.3,
            factors: { historicalDisasters: 3, rainfallImpact: 48, elevationVulnerability: 52, populationDensity: 62, infrastructureVulnerability: 46, distanceToEmergencyServices: 45, roadAccessibility: 85 }
        },
        {
            id: '892834d2d5bffff',
            name: 'Katrain Valley Agricultural Basin',
            sector: 'Central Valley Lowland Plain',
            lat: 32.1400,
            lng: 77.1550,
            elevation: 1750.0,
            baselineRisk: 38,
            currentRisk: 44,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 15200,
            vulnerablePopulation: { total: 4250, infants: 1150, elderly: 1700, disabled: 560, pregnant: 840 },
            carryingCapacity: 16000,
            safeCapacityThreshold: 18000,
            capacityDeficit: 0,
            nearestShelter: 'Katrain Agricultural Center Shelter',
            shelterCapacity: 9000,
            shelterDistanceKm: 1.4,
            evacuationTimeHours: 1.3,
            nearbyHospitals: ['Katrain Health Centre', 'Kullu Hospital (22km)'],
            roadStatus: 'Open',
            primaryRoad: 'NH-3 Katrain Arterial Link',
            rainfallMm: 180,
            waterLevelM: 0.2,
            factors: { historicalDisasters: 3, rainfallImpact: 44, elevationVulnerability: 48, populationDensity: 60, infrastructureVulnerability: 42, distanceToEmergencyServices: 35, roadAccessibility: 88 }
        },
        {
            id: '892834d2d5fffff',
            name: 'Naggar Lower Flank',
            sector: 'Naggar Base Foothills',
            lat: 32.1280,
            lng: 77.1650,
            elevation: 1810.0,
            baselineRisk: 36,
            currentRisk: 42,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 11600,
            vulnerablePopulation: { total: 3200, infants: 860, elderly: 1280, disabled: 420, pregnant: 640 },
            carryingCapacity: 12500,
            safeCapacityThreshold: 14000,
            capacityDeficit: 0,
            nearestShelter: 'Naggar Heritage Plateau Complex',
            shelterCapacity: 22000,
            shelterDistanceKm: 1.8,
            evacuationTimeHours: 1.2,
            nearbyHospitals: ['Naggar PHC (1.5km)'],
            roadStatus: 'Open',
            primaryRoad: 'Naggar Road Link',
            rainfallMm: 175,
            waterLevelM: 0.2,
            factors: { historicalDisasters: 2, rainfallImpact: 42, elevationVulnerability: 44, populationDensity: 55, infrastructureVulnerability: 40, distanceToEmergencyServices: 30, roadAccessibility: 90 }
        },
        {
            id: '892834d2d63ffff',
            name: 'Chachogi Mid-Mountain Terrace',
            sector: 'Eastern Valley Slope',
            lat: 32.2500,
            lng: 77.2150,
            elevation: 2240.0,
            baselineRisk: 45,
            currentRisk: 52,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 9400,
            vulnerablePopulation: { total: 2600, infants: 700, elderly: 1040, disabled: 340, pregnant: 520 },
            carryingCapacity: 10200,
            safeCapacityThreshold: 11500,
            capacityDeficit: 0,
            nearestShelter: 'Vashisht High Thermal Relief Hub',
            shelterCapacity: 18000,
            shelterDistanceKm: 2.2,
            evacuationTimeHours: 1.5,
            nearbyHospitals: ['Civil Hospital Manali (4km)'],
            roadStatus: 'Open',
            primaryRoad: 'Chachogi Rural Access Road',
            rainfallMm: 210,
            waterLevelM: 0.1,
            factors: { historicalDisasters: 3, rainfallImpact: 52, elevationVulnerability: 50, populationDensity: 52, infrastructureVulnerability: 46, distanceToEmergencyServices: 40, roadAccessibility: 78 }
        },
        {
            id: '892834d2d67ffff',
            name: 'Nasogi Pine Ridge Foot',
            sector: 'Western Hillside Base',
            lat: 32.2350,
            lng: 77.1780,
            elevation: 2110.0,
            baselineRisk: 34,
            currentRisk: 40,
            riskLevel: 'moderate',
            hazardType: 'Hydrological Watch',
            population: 8600,
            vulnerablePopulation: { total: 2400, infants: 640, elderly: 960, disabled: 310, pregnant: 490 },
            carryingCapacity: 9500,
            safeCapacityThreshold: 10500,
            capacityDeficit: 0,
            nearestShelter: 'ABVIMAS High Mountain Campus',
            shelterCapacity: 30000,
            shelterDistanceKm: 1.4,
            evacuationTimeHours: 1.1,
            nearbyHospitals: ['Civil Hospital Manali (2km)'],
            roadStatus: 'Open',
            primaryRoad: 'Nasogi Forest Road (Open)',
            rainfallMm: 165,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 2, rainfallImpact: 40, elevationVulnerability: 42, populationDensity: 50, infrastructureVulnerability: 38, distanceToEmergencyServices: 25, roadAccessibility: 92 }
        },

        // GREEN SAFE SANCTUARIES (High-Ground Receiving Havens with Large Surplus Buffers)
        {
            id: '892834d2d01ffff',
            name: 'Atal Tunnel South Portal Safe Complex',
            sector: 'High Altitude Rock Fortress Hub',
            lat: 32.3120,
            lng: 77.1320,
            elevation: 3060.0,
            baselineRisk: 14,
            currentRisk: 18,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 4500,
            vulnerablePopulation: { total: 1100, infants: 280, elderly: 440, disabled: 150, pregnant: 230 },
            carryingCapacity: 69500,
            safeCapacityThreshold: 75000,
            capacityDeficit: 0,
            surplusCapacity: 65000,
            nearestShelter: 'Atal Tunnel South Portal Logistics Complex & Tunnel Hangar',
            shelterCapacity: 38000,
            shelterDistanceKm: 0.3,
            evacuationTimeHours: 0.4,
            nearbyHospitals: ['Atal Tunnel Medical Emergency Trauma Unit', 'BRO Project Deepak Base'],
            roadStatus: 'Open',
            primaryRoad: 'Manali-Solang-Atal Tunnel High Expressway (Open 4-Lane)',
            rainfallMm: 110,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 0, rainfallImpact: 18, elevationVulnerability: 12, populationDensity: 15, infrastructureVulnerability: 14, distanceToEmergencyServices: 10, roadAccessibility: 98 }
        },
        {
            id: '892834d2d03ffff',
            name: 'ABVIMAS High Mountaineering Campus (Manali)',
            sector: 'Manali Pine Crest Safe Sanctuary',
            lat: 32.2250,
            lng: 77.1780,
            elevation: 2180.0,
            baselineRisk: 12,
            currentRisk: 15,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 8200,
            vulnerablePopulation: { total: 2100, infants: 550, elderly: 840, disabled: 290, pregnant: 420 },
            carryingCapacity: 63200,
            safeCapacityThreshold: 70000,
            capacityDeficit: 0,
            surplusCapacity: 55000,
            nearestShelter: 'ABVIMAS (Atal Bihari Vajpayee Mountaineering Institute) Mega Relief Ground',
            shelterCapacity: 30000,
            shelterDistanceKm: 0.4,
            evacuationTimeHours: 0.5,
            nearbyHospitals: ['Mission Hospital Manali (1.2km)', 'Lady Willingdon Hospital (1.5km)'],
            roadStatus: 'Open',
            primaryRoad: 'ABVIMAS High Ridge Spine Expressway (Open)',
            rainfallMm: 120,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 0, rainfallImpact: 15, elevationVulnerability: 14, populationDensity: 28, infrastructureVulnerability: 12, distanceToEmergencyServices: 12, roadAccessibility: 96 }
        },
        {
            id: '892834d2d05ffff',
            name: 'Vashisht Thermal High Ridge',
            sector: 'Northeastern Elevated Ridge Crest',
            lat: 32.2630,
            lng: 77.1970,
            elevation: 2220.0,
            baselineRisk: 16,
            currentRisk: 20,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 7400,
            vulnerablePopulation: { total: 1950, infants: 510, elderly: 780, disabled: 270, pregnant: 390 },
            carryingCapacity: 49400,
            safeCapacityThreshold: 55000,
            capacityDeficit: 0,
            surplusCapacity: 42000,
            nearestShelter: 'Vashisht Higher Ground Primary Relief Hub',
            shelterCapacity: 18000,
            shelterDistanceKm: 0.5,
            evacuationTimeHours: 0.6,
            nearbyHospitals: ['Vashisht Thermal Health Unit', 'Civil Hospital Manali (2.8km)'],
            roadStatus: 'Open',
            primaryRoad: 'Vashisht Thermal High Bypass Road (Open)',
            rainfallMm: 130,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 1, rainfallImpact: 20, elevationVulnerability: 16, populationDensity: 25, infrastructureVulnerability: 18, distanceToEmergencyServices: 20, roadAccessibility: 94 }
        },
        {
            id: '892834d2d07ffff',
            name: 'Solang High Alpine Plateau',
            sector: 'Upper Solang Valley Haven',
            lat: 32.3240,
            lng: 77.1480,
            elevation: 2650.0,
            baselineRisk: 18,
            currentRisk: 22,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 5800,
            vulnerablePopulation: { total: 1500, infants: 390, elderly: 600, disabled: 210, pregnant: 300 },
            carryingCapacity: 43800,
            safeCapacityThreshold: 50000,
            capacityDeficit: 0,
            surplusCapacity: 38000,
            nearestShelter: 'Solang Alpine Logistics Complex & Helipad Camp',
            shelterCapacity: 25000,
            shelterDistanceKm: 0.6,
            evacuationTimeHours: 0.7,
            nearbyHospitals: ['Solang Alpine Emergency Dispensary'],
            roadStatus: 'Open',
            primaryRoad: 'Solang High Elevated Bypass (Open)',
            rainfallMm: 125,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 1, rainfallImpact: 22, elevationVulnerability: 18, populationDensity: 20, infrastructureVulnerability: 16, distanceToEmergencyServices: 25, roadAccessibility: 92 }
        },
        {
            id: '892834d2d09ffff',
            name: 'Naggar Heritage Plateau & Castle Safe Zone',
            sector: 'Historic High Rock Terrace',
            lat: 32.1380,
            lng: 77.1750,
            elevation: 2050.0,
            baselineRisk: 12,
            currentRisk: 16,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 9100,
            vulnerablePopulation: { total: 2400, infants: 620, elderly: 960, disabled: 330, pregnant: 490 },
            carryingCapacity: 57100,
            safeCapacityThreshold: 65000,
            capacityDeficit: 0,
            surplusCapacity: 48000,
            nearestShelter: 'Naggar Heritage Government Complex & Grounds',
            shelterCapacity: 22000,
            shelterDistanceKm: 0.5,
            evacuationTimeHours: 0.5,
            nearbyHospitals: ['Naggar Primary Health Centre (PHC)'],
            roadStatus: 'Open',
            primaryRoad: 'Naggar Heritage High Spine (Open)',
            rainfallMm: 115,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 0, rainfallImpact: 16, elevationVulnerability: 14, populationDensity: 26, infrastructureVulnerability: 14, distanceToEmergencyServices: 18, roadAccessibility: 95 }
        },
        {
            id: '892834d2d11ffff',
            name: 'Dhundi Elevated Mountain Base',
            sector: 'Northwestern High Glacial Foreland',
            lat: 32.3320,
            lng: 77.1240,
            elevation: 2840.0,
            baselineRisk: 20,
            currentRisk: 24,
            riskLevel: 'safe',
            hazardType: 'Safe Refuge Sanctuary',
            population: 3200,
            vulnerablePopulation: { total: 820, infants: 210, elderly: 330, disabled: 110, pregnant: 170 },
            carryingCapacity: 37200,
            safeCapacityThreshold: 42000,
            capacityDeficit: 0,
            surplusCapacity: 34000,
            nearestShelter: 'Dhundi SASE High Altitude Relief Camp',
            shelterCapacity: 15000,
            shelterDistanceKm: 0.8,
            evacuationTimeHours: 0.8,
            nearbyHospitals: ['SASE / DRDO Mountain Infirmary'],
            roadStatus: 'Open',
            primaryRoad: 'Dhundi Strategic High Road (Open)',
            rainfallMm: 135,
            waterLevelM: 0.0,
            factors: { historicalDisasters: 0, rainfallImpact: 24, elevationVulnerability: 20, populationDensity: 12, infrastructureVulnerability: 15, distanceToEmergencyServices: 30, roadAccessibility: 90 }
        }
    ];

    // Arterial Road Networks across Manali (Beas River Valley & Rohtang Corridor)
    const roadNetwork = [
        { id: 'ROAD-01', name: 'NH-3 Chandigarh-Manali-Leh Arterial Highway', fromCell: '892834d2d33ffff', toCell: '892834d2d37ffff', status: 'Submerged', lanes: 2, maxFlowPph: 0, riskMultiplier: 5.2 },
        { id: 'ROAD-02', name: 'Old Manali Wooden Bridge Approach Road', fromCell: '892834d2d37ffff', toCell: '892834d2d2bffff', status: 'Submerged', lanes: 2, maxFlowPph: 0, riskMultiplier: 4.8 },
        { id: 'ROAD-03', name: 'Manali-Solang-Atal Tunnel High Expressway (Bypass)', fromCell: '892834d2d37ffff', toCell: '892834d2d01ffff', status: 'Open', lanes: 4, maxFlowPph: 7200, riskMultiplier: 1.0 },
        { id: 'ROAD-04', name: 'Left Bank Naggar-Manali Alternate Highway', fromCell: '892834d2d37ffff', toCell: '892834d2d09ffff', status: 'Congested', lanes: 2, maxFlowPph: 3600, riskMultiplier: 2.1 },
        { id: 'ROAD-05', name: 'Rohtang Pass Highway via Marhi (NH-3 Old)', fromCell: '892834d2d2bffff', toCell: '892834d2d1bffff', status: 'Damaged', lanes: 2, maxFlowPph: 500, riskMultiplier: 4.2 },
        { id: 'ROAD-06', name: 'ABVIMAS High Ridge Spine Expressway', fromCell: '892834d2d37ffff', toCell: '892834d2d03ffff', status: 'Open', lanes: 4, maxFlowPph: 6800, riskMultiplier: 1.0 },
        { id: 'ROAD-07', name: 'Vashisht Thermal High Bypass Road', fromCell: '892834d2d3fffff', toCell: '892834d2d05ffff', status: 'Open', lanes: 2, maxFlowPph: 4500, riskMultiplier: 1.1 },
        { id: 'ROAD-08', name: 'Palchan-Kothi Ridge Connector Road', fromCell: '892834d2d27ffff', toCell: '892834d2d07ffff', status: 'Open', lanes: 2, maxFlowPph: 4200, riskMultiplier: 1.2 }
    ];

    // Dedicated Emergency Shelters across Manali
    const shelters = [
        { id: 'SH-01', name: 'Atal Tunnel South Portal Logistics Complex & Tunnel Hangar', cellId: '892834d2d01ffff', capacity: 38000, currentOccupancy: 8200, availableCapacity: 29800, status: 'Active Reception', foodWaterDays: 30, medicalUnits: 20, powerBackup: 'Dual 500kVA GenSet + Dedicated Tunnel Grid' },
        { id: 'SH-02', name: 'ABVIMAS (Atal Bihari Vajpayee Mountaineering Institute) Mega Relief Ground', cellId: '892834d2d03ffff', capacity: 30000, currentOccupancy: 6100, availableCapacity: 23900, status: 'Active Reception', foodWaterDays: 25, medicalUnits: 16, powerBackup: 'High Power GenSet + Solar Microgrid' },
        { id: 'SH-03', name: 'Solang Alpine Logistics Complex & Helipad Camp', cellId: '892834d2d07ffff', capacity: 25000, currentOccupancy: 4800, availableCapacity: 20200, status: 'Active Reception', foodWaterDays: 22, medicalUnits: 14, powerBackup: 'Dual Diesel GenSets' },
        { id: 'SH-04', name: 'Naggar Heritage Government Complex & Grounds', cellId: '892834d2d09ffff', capacity: 22000, currentOccupancy: 4100, availableCapacity: 17900, status: 'Active Reception', foodWaterDays: 28, medicalUnits: 12, powerBackup: 'Independent Generator Station' },
        { id: 'SH-05', name: 'Vashisht Higher Ground Primary Relief Hub', cellId: '892834d2d05ffff', capacity: 18000, currentOccupancy: 3400, availableCapacity: 14600, status: 'Active Reception', foodWaterDays: 20, medicalUnits: 10, powerBackup: 'GenSet + Inverter Grid' },
        { id: 'SH-06', name: 'Manali Mall Road Municipal Town Hall', cellId: '892834d2d37ffff', capacity: 4000, currentOccupancy: 4000, availableCapacity: 0, status: 'AT CAPACITY BREACH', foodWaterDays: 2, medicalUnits: 3, powerBackup: 'Submerged / Generator Offline' },
        { id: 'SH-07', name: 'Palchan Forward Ground', cellId: '892834d2d27ffff', capacity: 2500, currentOccupancy: 2500, availableCapacity: 0, status: 'COMPROMISED (River Cutting)', foodWaterDays: 3, medicalUnits: 2, powerBackup: 'Solar Inverter Only' }
    ];

    // Major Hospitals & Medical Facilities in Manali & Kullu Valley
    const hospitals = [
        { id: 'HOSP-01', name: 'Civil Hospital Manali (Left Bank Watch)', cellId: '892834d2d37ffff', beds: 150, icuBeds: 18, availableIcu: 2, traumaCare: 'Level 2 Trauma Centre', status: 'HIGH LOAD / WATER PERIMETER WATCH', lat: 32.241, lng: 77.191 },
        { id: 'HOSP-02', name: 'Mission Hospital Manali (Old Manali)', cellId: '892834d2d2bffff', beds: 80, icuBeds: 8, availableIcu: 0, traumaCare: 'Level 3 Rural Emergency', status: 'INOPERATIVE (Basement Inundated)', lat: 32.244, lng: 77.194 },
        { id: 'HOSP-03', name: 'Regional Hospital Kullu (Major Referral Center)', cellId: '892834d2d09ffff', beds: 500, icuBeds: 60, availableIcu: 24, traumaCare: 'Level 1 Trauma Centre', status: 'Optimal / Safe Valley Base', lat: 32.050, lng: 77.160 },
        { id: 'HOSP-04', name: 'Lady Willingdon Hospital (Manali Safe Ridge)', cellId: '892834d2d03ffff', beds: 120, icuBeds: 15, availableIcu: 6, traumaCare: 'Level 2 Trauma', status: 'Operational / Safe Corridor', lat: 32.235, lng: 77.185 },
        { id: 'HOSP-05', name: 'Atal Tunnel South Portal Emergency Trauma Unit', cellId: '892834d2d01ffff', beds: 60, icuBeds: 12, availableIcu: 8, traumaCare: 'Level 2 Alpine Trauma', status: 'Optimal / Safe Rock Base', lat: 32.313, lng: 77.133 },
        { id: 'HOSP-06', name: 'Solang Alpine Emergency Dispensary', cellId: '892834d2d07ffff', beds: 40, icuBeds: 6, availableIcu: 3, traumaCare: 'Level 3 Emergency', status: 'Active / Safe Zone', lat: 32.324, lng: 77.149 },
        { id: 'HOSP-07', name: 'Naggar Primary Health Centre (PHC)', cellId: '892834d2d09ffff', beds: 50, icuBeds: 6, availableIcu: 4, traumaCare: 'Level 3 Emergency', status: 'Optimal / Safe Heritage Ridge', lat: 32.138, lng: 77.174 }
    ];

    // Emergency Response Teams & Specialized Himalayan Assets
    const emergencyResources = [
        { id: 'RES-01', type: 'NDRF 14th Battalion (Himachal Pradesh Swift Water Platoon)', category: 'Swift Water & Mountain Rescue', units: 16, boats: 22, personnel: 160, deployedCell: '892834d2d37ffff', status: 'Active Rescue', task: 'Evacuating flooded Old Manali commercial core' },
        { id: 'RES-02', type: 'Indian Army Western Command (Dogra Engineers & Bailey Bridge Taskforce)', category: 'Heavy Amphibious & Bailey Bridge Taskforce', units: 12, helo: 6, personnel: 320, deployedCell: '892834d2d2bffff', status: 'Active Extraction', task: 'Operating Old Manali airbridge & footbridge installation' },
        { id: 'RES-03', type: 'SDRF Himachal Pradesh Quick Reaction Alpine Rescue', category: 'Alpine Search & Evacuation', units: 14, vehicles: 26, personnel: 120, deployedCell: '892834d2d27ffff', status: 'Active Rescue', task: 'Palchan and Solang gorge slope search and extraction' },
        { id: 'RES-04', type: 'IAF Rotary Wing Western Command (Bhuntar Airport - Solang Airbridge)', category: 'Airborne Medical Evacuation (MI-17 / ALH Dhruv)', units: 8, helo: 8, personnel: 48, deployedCell: '892834d2d01ffff', status: 'Active Airbridge', task: 'Atal Tunnel South Portal to Bhuntar trauma airlift' },
        { id: 'RES-05', type: 'HRTC (Himachal Road Transport Corp) Mountain Evacuation Fleet', category: 'High-Altitude Bus & Heavy Convoy', units: 90, buses: 90, personnel: 135, deployedCell: '892834d2d03ffff', status: 'Active Transit', task: 'Shuttling evacuees from Manali bypass to ABVIMAS Campus' },
        { id: 'RES-06', type: '108 Advanced Life Support (ALS) Mountain Ambulances (Kullu Fleet)', category: 'Critical Care Mobile Units', units: 32, ambulances: 32, personnel: 64, deployedCell: '892834d2d03ffff', status: 'Dispatched', task: 'Transferring ICU patients from Manali to Kullu Regional Hospital' },
        { id: 'RES-07', type: 'BRO (Border Roads Organisation Project Deepak)', category: 'Road Clearance & Rock-Excavation', units: 20, bulldozers: 32, personnel: 175, deployedCell: '892834d2d1bffff', status: 'Debris Clearance', task: 'Clearing landslide debris on Rohtang Highway Marhi stretch' },
        { id: 'RES-08', type: 'CWC (Central Water Commission) Beas Basin Sensor Grid', category: 'Hydrological Telemetry Sensor Squad', units: 8, sensors: 16, personnel: 16, deployedCell: '892834d2d37ffff', status: 'Continuous Telemetry', task: 'Monitoring Beas River flood surge velocity and Solang discharge' }
    ];

    // Historical Disasters in the Manali Beas River Valley
    const historicalDisasters = [
        {
            year: 2023,
            name: 'Catastrophic Beas River Monsoon Deluge (July 2023)',
            type: 'Cloudburst & Riverine Deluge Surge',
            affectedPopulation: 92000,
            criticalCellsBreached: 8,
            peakRainfallMm: 360,
            evacuationTotal: 34500,
            relocationTotal: 52000,
            maxCarryingCapacityDeficit: 88000,
            durationDays: 7,
            keyLearning: 'Beas River overflowed banks washing away NH-3, bridges, and commercial riverbed hotels; established necessity for pre-emptive high-ground ridge relocation to ABVIMAS and Atal Tunnel.'
        },
        {
            year: 2022,
            name: 'Solang Valley Cloudburst & Flash Surge',
            type: 'Cloudburst & Debris Flow',
            affectedPopulation: 38000,
            criticalCellsBreached: 5,
            peakRainfallMm: 280,
            evacuationTotal: 16800,
            relocationTotal: 21000,
            maxCarryingCapacityDeficit: 35000,
            durationDays: 4,
            keyLearning: 'Palchan bridge washed away in 45 minutes; proved that low-lying rivermeanders must be vacated before peak precipitation.'
        },
        {
            year: 2018,
            name: 'Severe Beas Inundation & Rohtang Highway Severance',
            type: 'Compound Slope Slump & River Inundation',
            affectedPopulation: 46000,
            criticalCellsBreached: 6,
            peakRainfallMm: 310,
            evacuationTotal: 19500,
            relocationTotal: 26000,
            maxCarryingCapacityDeficit: 42000,
            durationDays: 5,
            keyLearning: 'Old Manali and Aleo sectors cut off from mainland Kullu; verified that Left Bank Naggar bypass is essential alternative corridor.'
        },
        {
            year: 2014,
            name: 'Kullu-Manali Monsoon Flash Floods & Slope Failures',
            type: 'Flash Flood & Debris Inundation',
            affectedPopulation: 58000,
            criticalCellsBreached: 7,
            peakRainfallMm: 295,
            evacuationTotal: 22000,
            relocationTotal: 31000,
            maxCarryingCapacityDeficit: 49000,
            durationDays: 6,
            keyLearning: 'Highlighted need for discrete H3 spatial carrying capacity limits to prevent overcrowding of relief camps.'
        }
    ];

    // Relocation Matching Allocations for Manali (Deficit Cells -> Safe High Ridges)
    // Categorized across the 3 SIH26191 Planning Horizons: Immediate (<24h), Short-Term (1-4w), and Medium-Term (3-12m)
    const relocationAllocations = [
        // 🔴 TIER 1: IMMEDIATE RELOCATION (<24h / Active Life-Threat Breach)
        {
            sourceCellId: '892834d2d2bffff', // Old Manali Bridge & Curve (Deficit: 13,250)
            targetCellId: '892834d2d03ffff', // ABVIMAS High Campus (Surplus: 55,000)
            allocatedPopulation: 13250,
            distanceKm: 2.1,
            travelTimeMinutes: 18,
            corridorStatus: 'ABVIMAS High Mountain Spine Bypass (Open)',
            medicalSupport: 'Lady Willingdon Hospital & ABVIMAS Field Unit',
            priority: 'P1 - Immediate',
            relocationHorizon: 'Immediate',
            horizonBadge: 'Immediate (<24h)',
            transitMode: 'HRTC Mountain Evacuation Bus Fleet & 4x4 Convoys'
        },
        {
            sourceCellId: '892834d2d37ffff', // Beas Riverbed Lowland Core (Deficit: 22,700)
            targetCellId: '892834d2d01ffff', // Atal Tunnel South Portal Safe Complex (Surplus: 65,000)
            allocatedPopulation: 22700,
            distanceKm: 16.5,
            travelTimeMinutes: 35,
            corridorStatus: 'Manali-Solang-Atal Tunnel High Expressway (Open)',
            medicalSupport: 'Atal Tunnel South Portal Emergency Trauma Centre',
            priority: 'P1 - Immediate',
            relocationHorizon: 'Immediate',
            horizonBadge: 'Immediate (<24h)',
            transitMode: 'HRTC Heavy Evacuation Fleet + Army Convoys'
        },
        {
            sourceCellId: '892834d2d3fffff', // Bahang Inundation Embankment (Deficit: 17,000)
            targetCellId: '892834d2d05ffff', // Vashisht Thermal High Ridge (Surplus: 42,000)
            allocatedPopulation: 17000,
            distanceKm: 3.2,
            travelTimeMinutes: 20,
            corridorStatus: 'Vashisht Thermal High Bypass Road (Open)',
            medicalSupport: 'Vashisht Thermal Relief Health Post',
            priority: 'P1 - Immediate',
            relocationHorizon: 'Immediate',
            horizonBadge: 'Immediate (<24h)',
            transitMode: 'Civil Defence Shuttles & NDRF High-Ground Convoys'
        },

        // 🟠 TIER 2: SHORT-TERM RELOCATION (1–4 Weeks / Pre-Monsoon Staging & Saturated Toe Slopes)
        {
            sourceCellId: '892834d2d27ffff', // Palchan Cloudburst Confluence (Deficit: 10,700)
            targetCellId: '892834d2d07ffff', // Solang High Alpine Plateau (Surplus: 38,000)
            allocatedPopulation: 10700,
            distanceKm: 4.5,
            travelTimeMinutes: 24,
            corridorStatus: 'Palchan-Kothi Ridge Connector (Open)',
            medicalSupport: 'Solang Alpine Dispensary & Relief Base',
            priority: 'P2 - Staged',
            relocationHorizon: 'Short-Term',
            horizonBadge: 'Short-Term (1-4w)',
            transitMode: 'SDRF All-Terrain Mountain Vehicles'
        },
        {
            sourceCellId: '892834d2d1bffff', // Marhi Landslide Chute (Deficit: 6,200)
            targetCellId: '892834d2d01ffff', // Atal Tunnel South Portal Safe Complex
            allocatedPopulation: 6200,
            distanceKm: 9.8,
            travelTimeMinutes: 38,
            corridorStatus: 'Atal Tunnel West Spur Bypass',
            medicalSupport: 'Atal Tunnel Medical Emergency Trauma Unit',
            priority: 'P2 - Staged',
            relocationHorizon: 'Short-Term',
            horizonBadge: 'Short-Term (1-4w)',
            transitMode: 'Army 4x4 Troop Carriers & BRO Shuttles'
        },

        // 🟡 TIER 3: MEDIUM-TERM RELOCATION (3–12 Months / Permanent Planned Resettlement)
        {
            sourceCellId: '892834d2d33ffff', // Aleo Riverside (Deficit: 15,700)
            targetCellId: '892834d2d09ffff', // Naggar Heritage Plateau (Surplus: 48,000)
            allocatedPopulation: 15700,
            distanceKm: 18.2,
            travelTimeMinutes: 42,
            corridorStatus: 'Left Bank Naggar-Manali Alternate Highway (Open)',
            medicalSupport: 'Naggar Primary Health Centre (PHC)',
            priority: 'P3 - Planned',
            relocationHorizon: 'Medium-Term',
            horizonBadge: 'Medium-Term (3-12m)',
            transitMode: 'Civil Administration Planned Resettlement Convoy'
        },
        {
            sourceCellId: '892834d2d47ffff', // Klash - 15 Mile Meander (Deficit: 7,200)
            targetCellId: '892834d2d09ffff', // Naggar Heritage Plateau
            allocatedPopulation: 7200,
            distanceKm: 14.5,
            travelTimeMinutes: 32,
            corridorStatus: 'Left Bank Alternate Highway',
            medicalSupport: 'Naggar Primary Health Centre',
            priority: 'P3 - Planned',
            relocationHorizon: 'Medium-Term',
            horizonBadge: 'Medium-Term (3-12m)',
            transitMode: 'State Housing Rehabilitation Program'
        },
        {
            sourceCellId: '892834d2d4fffff', // Prini Left Bank Slope (Deficit: 5,700)
            targetCellId: '892834d2d03ffff', // ABVIMAS High Campus
            allocatedPopulation: 5700,
            distanceKm: 4.8,
            travelTimeMinutes: 22,
            corridorStatus: 'ABVIMAS High Ridge Link',
            medicalSupport: 'Civil Hospital Manali & ABVIMAS Clinic',
            priority: 'P3 - Planned',
            relocationHorizon: 'Medium-Term',
            horizonBadge: 'Medium-Term (3-12m)',
            transitMode: 'SDMA Permanent Relocation Transit'
        }
    ];

    // If H3 Engine is loaded, generate Manali H3 grid
    const tessellatedGrid = (window.H3_ENGINE && typeof window.H3_ENGINE.generateManaliHexGrid === 'function')
        ? window.H3_ENGINE.generateManaliHexGrid()
        : ((window.H3_ENGINE && typeof window.H3_ENGINE.generateSikkimHexGrid === 'function')
            ? window.H3_ENGINE.generateSikkimHexGrid()
            : h3Cells);

    return {
        h3Cells: tessellatedGrid,
        fallbackH3Cells: h3Cells,
        roadNetwork,
        shelters,
        hospitals,
        emergencyResources,
        historicalDisasters,
        relocationAllocations
    };
})();
